### ISSUE TITLE
No Ocean Monuments or Mansions?

### ISSUE THREAD

**Issue by Galindorf** [Glitchfiend/BiomesOPlenty#1011]
BEFORE SUBMITTING!
----
For feature requests, please delete this template and create your own. If this is an issue, ensure the following before reporting:

- [ x] Biomes O' Plenty is updated to the latest available version
- [ x] This issue occurs with Minecraft 1.11. **WE DO NOT SUPPORT MINECRAFT 1.7.10, 1.8.9, 1.9.4, 1.10.2 AND ANY VERSIONS BELOW THAT!  YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**
- [X ] Forge is updated to the latest available version
- [ ] This issue occurs without Optifine, Cauldron or similar mods installed
- [x ] All other mods which appear to be involved are updated to their latest versions
- [x ] This issue does not occur in a modpack (If it does, please report this to the modpack author)
#### Issue Description:

I have generated several worlds and noticed that there are no ocean monuments to be found! I have also not run across any Desert Temples, or Roofed Forest Mansions. Is this a thing, or have I just been radically unlucky? 

#### Steps to reproduce:

1. Generate a New World
2. Fly Around a Lot of Ocean Biomes
3. Notice the Lack of Ocean Monuments

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
- Screenshots:

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.11.2-6.0.2.2164-universal
- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.0.2228

**Comment by Syndaryl** [comment]
Use the [locate](http://minecraft.gamepedia.com/Commands#locate) command to find structures if you're in doubt.

**Comment by Forstride** [comment]
Woodland Mansions do not generate yet, but I can confirm that ocean monuments do generated.

**Comment by Syndaryl** [comment]
I've seen a couple of Woodland Mansions...

**Comment by Galindorf** [comment]
Yeah, using the "locate" command I was able to find all of the items in question, but I don't know if it's because of where Minecraft thought they "should" (according to the algorithm) or if they would have generated in the chunks as I walked. On Vanilla minecraft (as of 1.10) you couldn't seem to swing a dead cat without hitting an ocean monument. I guess we've just been really unlucky!

**Comment by Syndaryl** [comment]
You can tell /locate is working correctly and not "conjuring" the features into being just because you ran it, because they get put in sensible biomes. It doesn't generate ocean monuments in Badlands, or Woodland Mansions in Mesas. BOPs world gen algorithm is _so_ different from vanilla, there's just no alignment of appropriate biomes (Except by staggeringly good fortune).

**Comment by Syndaryl** [comment]
You'll see a difference in Vanilla minecraft vs BOP simply due to distribution of biomes. More of the "ocean" isn't Deep Ocean - you get Coral Reefs and so forth, and those can't spawn Ocean Monuments. Further, depending on the world type you might just get less wide stretches of ocean!
Anything that depends on generating _only_ in Vanilla biomes will be less common, because now those Vanilla biomes are competing with the very large list of BOP biomes. That's just how it works.

It is, as they say, "Working as intended".

Adding BOP-equivalent versions of the Desert Temple in e.g. Outback or Steppe biomes, or Jungle Temple in e.g. Rainforest biome would be a "solution", but that's not a bug-fix, that's a big-honking-feature.

**Comment by Forstride** [comment]
"Adding BOP-equivalent versions of the Desert Temple in e.g. Outback or Steppe biomes, or Jungle Temple in e.g. Rainforest biome would be a "solution", but that's not a bug-fix, that's a big-honking-feature."

We don't really need to add "equivalents," we'd just allow those vanilla structures to generate in our similar biomes.  Adubbz was working on setting that up for the woodland mansions at one point, although IDK if he ever even finished it.

And of course, desert temples, jungle temples, igloos, etc. need to generate in our biomes as well.

**Comment by Forstride** [comment]
Woodland Mansions and other vanilla structures now generate in various BOP biomes.
