### ISSUE TITLE
buildcraft compatibillity

### ISSUE THREAD

**Issue by net4fun4ever** [Glitchfiend/BiomesOPlenty#1017]
#### Issue Description:
Hi, i'm using the new buildcraft alpha buildcraft-7.99.3 mod, and i get a crash on load.
I opened a issue on buildcraft, and found out that BiomesOPlenty is at fault here.

------------------------------------------------------
from buildcraft:
'it's a problem with another mod, someone is still returning null instead of an empty itemstack for pickblock'

https://github.com/BuildCraft/BuildCraft/issues/3569
------------------------------------------------------

As the buildcraft is still in alpha it works great with my modpack of 72 mods. Hope that BiomesOPlenty will be compatible with buildcraft in the future, because i know it takes a lot of time to code this kind of a great mod.

#### Steps to reproduce:

1.  deleted mod Biomes O' Plenty
2.  load Minecraft, everything is fine
3.  added mod Biomes O' Plenty
4. Minecraft returns an error while loading the game.

#### Additional Information:

[crash-2017-05-12_11.13.52-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/995814/crash-2017-05-12_11.13.52-client.txt)

#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 1.11.2-6.1.0.2213
- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.0.2296

**Comment by Adubbz** [comment]
The issue linked above mentions that someone is returning null instead of an empty itemstack for `getPickBlock`, and that is most certainly not BoP (Feel free to check https://github.com/Glitchfiend/BiomesOPlenty/search?utf8=%E2%9C%93&q=getPickBlock&type= ). Also there's this:

![screenshot from 2017-05-13 00-30-26](https://cloud.githubusercontent.com/assets/2765389/26002659/b9bc378c-3773-11e7-9b6e-570dd17fd0f4.png)

Some other mod is interfering, and I guess BoP just happens to get caught up in it.

**Comment by net4fun4ever** [comment]
Thats yust crazy :) Someone made an evil mod, someone doesnt like BoP. Tnx for your time
