### ISSUE TITLE
Biomes Json reseting

### ISSUE THREAD

**Issue by Mattabase** [Glitchfiend/BiomesOPlenty#1075]
#### Issue Description:

When editing a Biomes json file any changes made will be rolled back on launch. 
I tried doing something as simple as changing dirt to snow in a biome and it was undone. 

#### Steps to reproduce:

1.  Edit any Biome .json
2.  Launch the game

#### Additional Information:

https://goo.gl/mFpuks

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.0.2289
- Minecraft:  1.12
- Forge:  2413

**Comment by Adubbz** [comment]
This is intentional, those files are just meant to show the default values and structure of the json files, so you can copy certain parts into a file in /config/biomesoplenty/biomes based on what you want to change. See https://github.com/Glitchfiend/BiomesOPlenty/wiki/Configuring-Biomes for a better explanation

**Comment by Mattabase** [comment]
Thank you very much.

My bad =P
