### ISSUE TITLE
Broken links/Missing pages in wiki

### ISSUE THREAD

**Issue by Flubbles** [Glitchfiend/BiomesOPlenty#1148]
Crafting Recipes
Commands
Blocks
Items
Mobs

Are all missing pages, leading to the links not working.

**Comment by srs-bsns** [comment]
The wiki was never completed.

**Comment by Forstride** [comment]
I'm just gonna close this since it's not really pertaining to the mod itself, and I just don't really have time to devote to writing out a full detailed wiki for everything (Nor do I really want to honestly).  Maybe I'll get to it at some point, but in the mean time, there's an unofficial wiki that probably has any info you might need.
