### ISSUE TITLE
[1.12.2] NetherEx skips Biomes O'Plenty biomes in the nether

### ISSUE THREAD

**Issue by JonasCiss** [Glitchfiend/BiomesOPlenty#1149]
If Biomes O'Plenty is present NetherEx lets only appear its own biomes in the nether. All BOP features are skipped.

Can also be found here: [https://github.com/MineEx/NetherEx/issues/65](url)

**Comment by srs-bsns** [comment]
NetherEx uses their own custom chunk generator for the Nether with custom GenLayers, and their chunk generator overrides the vanilla Nether. Because of this, you will need to use their config files in order to add other mod's biomes to their Nether. See: https://www.reddit.com/r/NetherEx/wiki/configuration >> Biome Lists

**Comment by JonasCiss** [comment]
There are so mich options. Is there no way that NetherEx automatically registers all biomes?

**Comment by Sunconure11** [comment]
There's a script on the wiki with BoP biomes + NetherEx biomes

**Comment by JonasCiss** [comment]
Would you mind giving me a link?

**Comment by Sunconure11** [comment]
@JonasCiss https://www.reddit.com/r/NetherEx/wiki/configuration#wiki_premade_biome_lists

**Comment by JonasCiss** [comment]
Problem solved, thanks!
