### ISSUE TITLE
What currently do ALL the settings mean?

### ISSUE THREAD

**Issue by RepoDraghon** [Glitchfiend/BiomesOPlenty#1194]
I see like ¼ of the settings explained here [912](https://github.com/Glitchfiend/BiomesOPlenty/issues/912) however what are the Various "Scales"? also, the 3rd page is obvious, it's an on/off selector... although, a slider for rarity on each would be nicer...

**Comment by Forstride** [comment]
The scale sliders are the same as vanilla customized worlds: https://minecraft.gamepedia.com/Customized#Advanced_settings

As for the 3rd page, they're just toggles because they're features that a lot of people don't like, and we wanted them to be able to disable them easily.  You can change the frequency of individual plants for individual biomes with the biome config files though.
