### ISSUE TITLE
Boats can't be broken with bare hands

### ISSUE THREAD

**Issue by WesTroy** [Glitchfiend/BiomesOPlenty#1197]
#### Issue Description:

Thanks for all the great updates recently to your mods.

Love the boat textures. Two tiny things about BOP boats:
1. Can't break them by hand like vanilla boats. Axes work fine.
2. Can't use them as fuel. Vanilla boats burn for 400 ticks.

#### Affected Versions:

- Biomes O' Plenty: 1.12.2-7.0.1.2325
- Minecraft: 1.12.2
- Forge: 14.23.2.2624

**Comment by Forstride** [comment]
I fixed the fuel issue, but I'm not really sure what's causing the first issue.

Considering you can break it with an axe and not your bare hands, it seems like it's not saving the damage taken/time since it was last hit, and with the axe, it does enough damage to kill the boat in one/two hits.

Really not sure why, as the code is the exact same as vanilla boats.

**Comment by ProsperCraft** [comment]
I broke a boat with my bare hand just now.  Redwood variant.  It took a lot more hits then I would expect but it worked.

I had to use my hand because the atomic dissasembler was not working, which I would expect should.

**Comment by ProsperCraft** [comment]
Thank you.
