### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SimulatorSia** [Glitchfiend/BiomesOPlenty#1211]
Why was promised land removed? ;n;

**Comment by Forstride** [comment]
Please don't submit issues to ask questions like this.  Either ask us on Discord or Twitter.

They were removed because they were kind of out of the scope for the mod, and there were a lot of framerate issues due to the lighting system.

**Comment by SimulatorSia** [comment]
Why the heck can't I ask a question here since there are no comments allowed on your Curse post. If you get people asking questions here then it's your own fault and time to man up and simply answer them and be done with that.

About the promised land. My personal opinion is that it's not too far out of the scope of this pack and it made it really fun to get there on a modpack. If that dimension had lighting issues, why not use any other open source dimension code and just remake the procedural generation and there you go. I've been modding since Beta and owned several servers before so I fairly knowledgeable when it comes to balancing and themes. Most people who use Biomes o Plenty also use it with other mods and consequently other dimensions which then make the Promised land a very *not* out of place feature. You could add a little option in the config to disable it. Not just disable the crafting of the portal but probably should disable all the items from the promised land from even existing so JEI wouldn't pick them up.

**Comment by Adubbz** [comment]
We have a Discord  that is linked in the Curse post, specifically for asking questions. And though it's not ideal, there is our Twitters linked as well. It's not about manning up, it's about using different mediums for their intended purpose.

**Comment by SimulatorSia** [comment]
Think about it for two seconds. You'd rather push people to join your discord or send you messages on twitter concerning a minecraft mod instead of utilizing the #1 most popular minecraft modding related website ever. I don't see the logic. Everyone uses Curse and everyone likes the comment second but you've gotta push them outside the site to join your discord? Sorry if I repeat myself but I can't comprehend the stupidity and utter disregard. Sometimes people don't wanna be engaged directly with such a chat room. It is intimidating.

**Comment by Adubbz** [comment]
We don't care about how popular it is, we care about how convenient it is for us to use, which it is not at all.  You'll find that *many* other mods, especially large ones, also have comments disabled on their CurseForge pages. They're tacked on, and unhelpful. Also worth noting is that Github is a third party website and yet you seem to have no qualms about posting here... Doesn't make sense really.

**Comment by Forstride** [comment]
> If you get people asking questions here then it's your own fault and time to man up and simply answer them and be done with that.

I did answer you though.  Telling you not to ask simple questions here was for future reference.

> but you've gotta push them outside the site to join your discord

Yeah, sorry for wanting to lighten our daily load.  Having all discussion centralized in our Discord server makes everything much easier for us, because we'll actually see it.  We don't even check our Minecraft Forum thread anymore because aside from just not remembering, it became too much.

We don't even check the actual CurseForge page that often, because we just don't need to.  We have automatic builds that are compiled anytime we make a change to the mod, and get sent to CurseForge immediately.  If we had the comment section enabled, I can already tell you we would not be responding to people on there, as we just wouldn't even see the comments.

> It is intimidating.

Welp, guess it's time to for _you_ to "man up" then.
