### ISSUE TITLE
(Question) Recent Changes...

### ISSUE THREAD

**Issue by ate0ate** [Glitchfiend/BiomesOPlenty#1245]
Whilst perusing the ol' changelogs, I couldn't help but be a bit surprised by some of the more recent changes. I was wondering, why the removal of so many little tidbits such as the damp grass and wheat grass, turnips, jelled poison, the Polar Chasm biome, stalactites/stalagmites, and more? I am not asking you to justify each little change you make or anything of the sort. I was merely wondering, are these changes permanent, temporary removals to better tweak them, a preparation for 1.13, or more simply an attempt at trimming the fat from the mod a bit? Thank you for your time.

**Comment by vincania** [comment]
really good question... especially the grass variation was one of my favorite features... :(

**Comment by Forstride** [comment]
Yes, they are permanent.  Any time I remove something, it's because I don't like it anymore.  The main reason for that is usually because they add too much clutter to the mod, but it could just simply be because I feel like it impacts the mod's design as a whole negatively.

See, there was a point in time where I wanted to just add a ton of content, like different grass varieties, foods, and so on, cause I felt like more detail and decoration was better, but now a lot of it just feels too cluttered and messy.  For example, biomes, especially grassy plains, look a LOT better without wheat/damp grass to me.  There's a lot less "noise," and everything feels much more cohesive.

Other times, stuff gets removed because it's out of the scope for the mod.  Over the years, we've had people complain about how the mod adds so much extra stuff that isn't directly tied to the biomes themselves, and I've started to agree with them.

Of course, people also complain about the mod adding plants or flowers or other decorative blocks that have no actual use outside of being decorative, but I think I'd rather have it be like that than try and add uses for them and end up adding a bunch of other content just for that.

I really hate talking about why things get removed from the mod, because people always say "why don't you just make another mod that re-adds it!"  But they don't seem to get that if I still liked the content I removed, I wouldn't have removed it in the first place.  I'm not going to make another mod with things that I feel are designed poorly just to please people.  I develop mods for my own satisfaction above all else, and if other people like it, great, but pleasing other people isn't something I really care about honestly.  Any artist is going to feel the same way.

Also, for future reference, please just ask stuff like this on our Discord server.  I really don't like issues being used to ask us basic questions like this.

**Comment by ate0ate** [comment]
I understand, and thank you for answering. I have no complaints to make and respect the decisions made with the mod. It only makes sense to better streamline things and change prevents stagnation.

I have played with this mod in various forms for years now and have seen it change many times. There's been things like the promised land, fantasy biomes, or the changes made to the End that have come and gone before and different ways that the mod has tried to branch out and then pulled back again. A more cohesive vision is never a bad thing. My main concern was simply the permanence/impermanence of these changes and therefore which build of the mod I should generate a world with.

I do apologize for posting here and will ask questions on discord from here on. Some mod authors get angry for asking questions like that there or on the forum and request github feedback only, others hate that and prefer forum only. There's really no winning and you end up pissing in someone's cornflakes no matter what decision you make:) Seriously though, thank you for your effort on the mod, and thank you again for answering. 

I've always enjoyed BoP and it will continue to be a staple in my modpacks for the foreseeable future, regardless of changes. The best mods are ones that aim at realizing the mod author's unique vision or something they are at least somewhat passionate about, not soulless people pleasing. I would place BoP in the former category. Cheers.
