### ISSUE TITLE
world.json config not taking effect

### ISSUE THREAD

**Issue by rawhide-k** [Glitchfiend/BiomesOPlenty#1247]
#### Issue Description:
world.json config settings do not take effect in release versions past 1.12.2-7.0.1.2350

#### Steps to reproduce:

1. change a setting from default in world.json
2. create a new world
3. cry at a world full of disparate grass blocks

#### Additional Information:

I assume this is due to the change in beta 1.12.2-7.0.1.2353, but I didn't test every beta version between the two release builds.

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.2-7.0.1.2355+
- Minecraft: 1.12.2
- Forge: 14.23.3.2655

**Comment by Forstride** [comment]
The options for soils, trees, etc. to use vanilla blocks instead of our blocks were removed.  It was just too annoying to keep updated (Since they required changes to be made per-biome), when most people didn't use them.  This can be still done using our biome config system, but you have to do it for every individual biome.
