### ISSUE TITLE
[1.14.4] Client crash when starting a new world. .IllegalArgumentException: bound must be positive  -- jigsaw.JigsawPattern.func_214944_a

### ISSUE THREAD

**Issue by ProsperCraft** [Glitchfiend/BiomesOPlenty#1475]
## Bug Report

[ ]</br>

### How can the crash be reproduced?

[Make a new world]</br>

This seems to be an edge case, and I can reproduce it every time with this world, but only with the full pack, I tried to add one mod at a time, but every load in gave a different looking world as I think each of the mods changed the world so it wasn't loading the biome that crashes unless you have the full pack.

[New World (23).zip](https://github.com/Glitchfiend/BiomesOPlenty/files/3721740/New.World.23.zip)

Google search for JigsawPattern.func_214944_a produced nothing.

I downloaded the source and searched inside the files for jigsaw and found nothing.

### Crash Report and Logs
Crash report-
https://gist.github.com/ProsperCraft/052389f088886974930c4584fa9510e0
[
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/3721702/latest.log)

]</br>

### Mod Version
[BiomesOPlenty-1.14.4-9.0.0.254-universal]</br>
forge-1.14.4-28.1.44
Modpack - https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by Forstride** [comment]
I mean, this doesn't seem to have anything to do with BOP inherently, and is caused by something with village generation (Which, we don't alter at all.  We just add villages to some of our biomes, and it's a single line of code for each one).

Sorry to say, but it's really on you to figure out exactly which mod is causing it, when BOP isn't in the stacktrace at all, **and** you're using other biome mods.  Hell, it might not even be caused by a mod.  It might just be something weird with vanilla, in which case, you should check the Minecraft Mojira issue tracker as well.

**Comment by maxanier** [comment]
This could indeed be caused by BOP, if it would add a village with an invalid configuration to it's biomes (see https://github.com/TeamLapen/Vampirism/issues/543#issuecomment-541435696)
E.g.
```
this.addStructure(Feature.VILLAGE, new VillageConfig("village/does/not/exist", 6));
```
or something less obvious (typo).
However, I went though all of BOPs overworld biomes and couldn't find a typo (might have missed something though)
