### ISSUE TITLE
[1.14.4] Server crash - java.lang.IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by ProsperCraft** [Glitchfiend/BiomesOPlenty#1508]
### How can the crash be reproduced?

[ Start a new world and let players generate terrain, once a player hits the area every time he logs in it crashes the server ]</br>

### Crash Report and Logs
[2019-12-15-2.log.gz](https://github.com/Glitchfiend/BiomesOPlenty/files/3965093/2019-12-15-2.log.gz)

https://gist.github.com/ProsperCraft/116a3c55815c8596d1d1ed0f8ba6a3b1
same player logging in again - https://gist.github.com/ProsperCraft/5bcdc8d6dd4427c8a50d707c96a1044a

Looks like this happened in the past - note we do not have Vampirism installed - 
https://github.com/Glitchfiend/BiomesOPlenty/issues/1475

### Mod Version
[ BiomesOPlenty-1.14.4-9.0.0.259-universal
Modpack - https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk
forge-1.14.4-28.1.104
]</br>

**Comment by Forstride** [comment]
This is basically the same exact issue you reported before...Which I already commented on, and you seemingly did nothing to try and investigate it further yourself.

It's on you to go through your mods and see which ones affect village generation or the jigsaw structure system, and remove them one by one and see if anything changes.  Because you are the only person who has had this issue, and there's nothing that directly links it to BOP.
