### ISSUE TITLE
Biomes O' Plenty Ocean generation issue

### ISSUE THREAD

**Issue by WeeGee-mc** [Glitchfiend/BiomesOPlenty#1509]
I've gotten an issue, in Biomes O' Plenty the ocean biomes are not there. Although, it says I'm on an ocean when on some vanilla mountains. But there is no ocean, just a beach attached to some vanilla hills.  I checked the config and there was no possible ay for me to fix this issue. If anyone can help me fix this, please do. The "Ocean" is a hill with coconut trees, ocean colored grass, crabs, and whales spawning in ponds. Here is a small picture of my issue:  https://ibb.co/grGphqY

**Comment by Forstride** [comment]
First of all, this almost certainly isn't caused by BOP.  Second, you didn't provide any info on what other mods you're using, what version of Minecraft you're using, etc.  Although I can tell it's not 1.14, which is the only version we support now anyway, as it says when you go to submit an issue...
