### ISSUE TITLE
Can't Fully Remove/ Uninstall Biomes O' Plenty 

### ISSUE THREAD

**Issue by ThatDoomGuy** [Glitchfiend/BiomesOPlenty#1538]
![Biomes O' Plenty Issue](https://user-images.githubusercontent.com/60489454/73492915-522ed380-43ba-11ea-9bf7-b514ea4fe803.png)

I tried Biomes O' Plenty and after a couple weeks I decided to uninstall it. 
However now every world I open it displays this even though the mod isn't in my mod folder. 
It even does this to new worlds I create. 

How can I fully remove/uninstall Biomes O' Plenty?

**Comment by Forstride** [comment]
Well existing worlds are going to show it because that stuff is saved in the world file.  You can click "Yes," but if any of those blocks or items are in it, they'll be replaced with air blocks.

As for new worlds, I'm not sure how Forge handles it, but it might be something weird with their config?  Just try clicking "Yes" and see if it goes away afterwards.

**Comment by Adubbz** [comment]
Given this is occurring after uninstalling the mod, this is expected behaviour and not a bug. The same will occur for any mods that add blocks or items and are later removed. Choosing yes will behave as Forstride described.
