### ISSUE TITLE
Error during the load_registries event phase

### ISSUE THREAD

**Issue by 12foot12** [Glitchfiend/BiomesOPlenty#1616]
So I made a small mod pack and included Biomes O' Plenty and encountered this error report.

[20May2020 12:08:16.541] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for modid biomesoplenty
java.lang.NoSuchMethodError: net.minecraft.item.MusicDiscItem.<init>(ILjava/util/function/Supplier;Lnet/minecraft/item/Item$Properties;)V
	at biomesoplenty.common.item.MusicDiscItemBOP.<init>(MusicDiscItemBOP.java:32) ~[?:?]
	at biomesoplenty.init.ModItems.registerItems(ModItems.java:31) ~[?:?]

Then proceeded to remove every mod except Biomes O' Plenty and got the same exact error. I have no idea what it's going on about a music disc. Heres both crash report with and without all the mods.
[standalone.log](https://github.com/Glitchfiend/BiomesOPlenty/files/4658895/standalone.log)
[crash with mods.log](https://github.com/Glitchfiend/BiomesOPlenty/files/4658898/crash.with.mods.log)

So far everytime I've launched it, which is more than a dozen times I've gotten that error.
Halp.
Version of Biomes O' Plenty: 10.0.0.362

**Comment by Nakesha** [comment]
I also tried to run this version of the mod and it gave me this error but I installed Forge 31.2.0 and it worked

**Comment by Forstride** [comment]
Update Forge

**Comment by AtlaStar** [comment]
Hey @Forstride do you think it would be worth the time to just write a lazyoptional that is set up during init so BOP has greater support for versions of Forge or to just use the new Forge API like currently is the case? I ask because my PR is what is causing the influx of issues and I am thinking I could submit a broader fix that would work across more versions of 1.15.x and use the current change for 1.16 and above.
