### ISSUE TITLE
Error during load registries event phase (MusicDisc)

### ISSUE THREAD

**Issue by zanyismm** [Glitchfiend/BiomesOPlenty#1617]
## Bug Report

My server will throw up this error message and fail to load with just BSP. Running the most recent version of forge and BSP, however, my game will load just fine. If I switch to an older version than my server will load but my client will crash.
https://imgur.com/a/P5s0hm5

### How can the crash be reproduced?
By hitting play with my version
### Crash Report and Logs

[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/4659218/latest.log)
[crash-2020-05-19_23.29.42-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/4659223/crash-2020-05-19_23.29.42-server.txt)

### Mod Version
Tried 358-362

**Comment by AtlaStar** [comment]
The latest version of BOP requires Forge 31.1.95 and above, and previous versions of BOP need versions of Forge lower than 31.1.95

I am going to work on a possible fix that will make BOP compatible across a larger version range of Forge since my commit is what caused a lot of these headaches.

For now though you can just upgrade Forge to the latest version since your error is due to running Forge 31.1.63 while running a later version of Forge
