### ISSUE TITLE
Way to re-add removed biomes

### ISSUE THREAD

**Issue by rougedarkdragon** [Glitchfiend/BiomesOPlenty#1645]
All of the biomes of BoP are incredible. However, many of them have been removed for clear or unclear reasons. 

There should be a way in the config to re-add all of these biomes. By default they should not appear, but if a player really wants they can turn on a biome. 

Some of the biomes that were removed were some of the best biomes in the mod. The Sacred Springs, for example, was like a mediator between the Ominous Woods and the Mystic Grove. The Boneyard, even though it was pointless, was still visually pleasing. A lot of players would really like to see these biomes return, and this would give them a way of getting them back.

**Comment by Forstride** [comment]
Any removed content is usually removed because I didn't like it anymore and felt it was a bad fit for the mod.

Re-adding and it having it off by default means absolutely nothing.  The content still has to be maintained and updated, and obviously made presentable for users, and I'm not going to do that for content I don't care about it.
