### ISSUE TITLE
An Easy Way to Put BoP on Pre-existing Worlds

### ISSUE THREAD

**Issue by CommandBlockGuru** [Glitchfiend/BiomesOPlenty#1653]
## Feature Request

[ An easier way to put BoP on already existing worlds ]</br>

### What feature are you suggesting?

[ Maybe, theres a mod config you can put in that says something along the lines of 'Allow BoP biomes in this world'. I don't know. I've been trying to put BoP in my 1.12.2 survival world and I can't find much on it. ]</br>

### Why should it be added?

[ It would make people like me who don't really know how to navigate the coding files on games be able to enjoy their worlds with your mod. Also, I know that it said on the beginning that you'll only do updates and bug fixes and all that with the latest version, but I have no clue how to add your mod to 1.12.2. ]</br>

**Comment by Forstride** [comment]
We don't support 1.12 anymore, as it says when submitting an issue.  Either way, you have to use an NBT editor to change the world type for the existing save.  The easier option is to just make a new world, because that's how the mod is intended to be used.  Otherwise, you're only going to get our biomes in new chunks, and there will be rough borders between the existing chunks.
