### ISSUE TITLE
Biomes O Plenty 1.16.3 crashes MC

### ISSUE THREAD

**Issue by SpooderGwen** [Glitchfiend/BiomesOPlenty#1714]
## Bug Report

I removed all mods and reinstalled Forge before installing Biomes O plenty. MC still says "Settings are experimental" and the game still crashes.

### How can the crash be reproduced?

[ Include a detailed step by step process for recreating your crash with only Biomes O' Plenty installed. ]</br>

### Crash Report and Logs

[ Please include your crash report and logs here. This can be done by dragging and dropping your log files and crash report files into the issue. ]</br>

### Mod Version
[ Please put the version of the mod you were using here. ]</br>

**Comment by Forstride** [comment]
I already told you in your last issue report that the experimental settings screen is *not* an issue.  It's a vanilla feature that will appear when using world gen add-ons, such as biome mods, and it literally does nothing other than warning you that experimental settings are not supported.

If your game is crashing, it is because of something else, and you have not provided a crash report or log or anything that can actually tell me what it is.
