### ISSUE TITLE
BoP preset doesn't generate other mods' biomes in the Nether nor the End

### ISSUE THREAD

**Issue by justKaisa** [Glitchfiend/BiomesOPlenty#1755]
### The issue

When the world preset is set to _Biomes O' Plenty_, the biomes from _Oh The Biomes You'll Go_ do generate in the Overworld, but not in the Nether.

### How can the issue be reproduced?

The only mods installed were BYG and BoP, on Forge 35.1.0. Nothing else at all.
I tried using /locatebiome.
Configs default, unchanged.

When using default preset, BoP biomes did generate just fine with BYG biomes.

### Mod Version
BiomesOPlenty-1.16.4-13.0.0.422
Forge 35.1.0
byg-1.1.5

_I don't know whether this is an issue on BYG's end or BoP's, so forgive me for that in advance_

**Comment by whatusernamenottopick** [comment]
I checked the End and the same issue seems to persist there as well...

**Comment by Forstride** [comment]
This isn't necessarily a fault with either mod, but there's not really a good way to handle this, as the Nether doesn't really have a proper biome list or anything by default.  It has some weird noise values for each biome or whatever, so we had to create our own system for our Nether biomes, which requires an override of the Nether dimension's biome provider.

I don't know how BYG handles their Nether biomes, but unless Forge implements some uniform way to handle Nether biomes, we're probably not going to do anything about support for other mods.  As for the End, it's probably another situation where they have their own End provider, but since we have our world type, it's set to use vanilla's End provider.

**Comment by whatusernamenottopick** [comment]
Oh, interesting, I wasn't aware of that, thank you for the answer.
But, I still wonder, since the default world preset lets both BYG and BOP generate their biomes in the Nether(when BYG has control over the Nether set in its config), there certainly is _some_ way..
I don't really know, sorry to bother you, it's just confusing that BYG generates both mods' biomes seemingly without issues.

**Comment by Filomaster** [comment]
I've experienced similar problem.
I've noticed it initially in my modpack with BYG and BOP, and I've started looking which mod could cause the trouble. After removing old configs and all mods beside BOP, problem with Nether dimensions was still there.

Biomes like Visceral Heap and Withered Abyss had been generated with BOP blocks, but there weren't any vertical flesh like structures in Visceral Heap.
I was able to find Crystalline Chasm and Undergrowth with /locatebiome but nothing was generated there. Even fog color stayed the same as in nearest biomes. Beside those biomes were really small.

Mod version:
BiomesOPlenty-1.16.4-13.0.0.425
Forge 35.1.13

**Comment by SheerAwesomeness** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/1765 would fix this - setting biome provider in config would allow the modpack creator to decide which mod controls the end, and by extension, the nether dimension biome generation.

Should be easy to implement, and have significant positive effect.

**Comment by Griefed** [comment]
> Should be easy to implement, and have significant positive effect.

I hate this phrase so much. If it's so easy, fork BOP, implement it and make a PR. Otherwise, please refrain from making such statements *if* you do not fully know whether it's easy or not.

It would be a great feature, on that I agree. Until then, one can also use the `Import Settings` feature and set the biome providers that way:
```json
{
  "dimensions": {
   "minecraft:overworld": {
      "generator": {
        "biome_source": {
          "seed": -8634566777844830259,
          "type": "minecraft:biomesoplenty_overworld"
        },
        "seed": -8634566777844830259,
        "settings": "minecraft:overworld",
        "type": "minecraft:noise"
      },
      "type": "minecraft:overworld"
    },
    "minecraft:the_nether": {
      "generator": {
        "biome_source": {
          "seed": -1660337403543655964,
          "type": "byg:bygnether"
        },
        "seed": -1660337403543655964,
        "settings": "minecraft:nether",
        "type": "minecraft:noise"
      },
      "type": "minecraft:the_nether"
    },
    "minecraft:the_end": {
      "generator": {
        "biome_source": {
          "seed": -1660337403543655964,
          "type": "byg:bygend"
        },
        "seed": -1660337403543655964,
        "settings": "minecraft:end",
        "type": "minecraft:noise"
      },
      "type": "minecraft:the_end"
    }
  },
  "seed": -8634566777844830259,
  "generate_features": true
}
```

Cheers,
Griefed

**Comment by SheerAwesomeness** [comment]
> I hate this phrase so much. If it's so easy, fork BOP, implement it and make a PR. Otherwise, please refrain from making such statements _if_ you do not fully know whether it's easy or not.

I went for the word "should" rather than "is" or similar. I'm not a mod developer, though do have significant Java experience. Therefore by assumption, it _should_ be easy to implement especially relative to the current features and other feature requests this repo already has. It will go a long way to providing some form of compatibility with other biome mods, or rather, a way to handle priority.

I may look into submitting a PR next week.

**Comment by Celophy** [comment]
i have the same bug

**Comment by Celophy** [comment]
still no solution?

**Comment by ShootToKillSTK** [comment]
Just gonna add that, with all newest versions of forge, BoP and Byg AND BetterEnd, Everything is working together except for nether biomes, tested both BoP and Byg configs (Disabling nether for bop, have Byg control it, having it not) 

And it's either No new nether biomes, just BoP's,  or import on world creation for Byg biomes in nether with BoP's (Aka everything working)

If there is a way to auto import on world making though I do not know, wish I did

**Comment by Forstride** [comment]
Closed since this issue isn't relevant on newer versions
