### ISSUE TITLE
Crash on modpack, odd crash

### ISSUE THREAD

**Issue by Dark-Strife** [Glitchfiend/BiomesOPlenty#1758]
## Bug Report

</br>

### How can the crash be reproduced?

Happened only when loading my modpack, never crashed like this before. Only crashed because of this mod.</br>

### Crash Report and Logs
[crash-2020-12-09_07.43.18-fml.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5665943/crash-2020-12-09_07.43.18-fml.txt)

### Mod Version
BiomesOPlenty-1.16.4-13.0.0.422-universal

**Comment by Dark-Strife** [comment]
also sorry if its not standalone, new on the site, followed the link from the crash report.

**Comment by BrisingrAerowing** [comment]
This seems to be a Forge thing, as I get it with pretty much any combination of mods.

**Comment by Vaelzan** [comment]
This is caused by BoP not having any thread-safety at all when registering compostables, flammables, etc.

They're loaded during the common setup event, which is run in parallel with other mods in Forge (and has been for quite a while now, since something like Minecraft 1.14 or so). Registering these things should be done by wrapping it similarly to this:

`
private void commonSetup(final FMLCommonSetupEvent event)
{
  event.enqueueWork(() -> {
    ModVanillaCompat.setup();
  }
}
`

The above would cause the vanilla compat to be run on the main thread instead of trying to do it at the same time as every other mod that happens to also lack thread safety.

**Comment by BrisingrAerowing** [comment]
Multithreaded mod loading is both a blessing and a curse.
