### ISSUE TITLE
[1.16.5] Nether biomes do not appear with TerraForged installed

### ISSUE THREAD

**Issue by MarioSMB** [Glitchfiend/BiomesOPlenty#1808]
### What's the issue you encountered?

TerraForged automatically populates worlds with biomes from other mods, Biomes O' Plenty biomes do indeed appear in the Overworld. However, in the Nether, no BoP biomes are shown, even with the `use_bop_nether` option set to true.  

### How can the issue be reproduced?

Launch a server with both TerraForged and Biomes O' Plenty installed, and the level-type set to terraforged. The mod's biomes will correctly show in the Overworld, but not in the Nether.

### Mod Version
13.0.0.431

**Comment by MarioSMB** [comment]
I understand this may seem like a TerraForged issue, however their team has elected to [ignore it](https://github.com/TerraForged/tracker/issues/44) and revert any attempts to clarify [workarounds](https://github.com/TerraForged/community/wiki/Forge-Server/_compare/afe967d929945699cb78d1ad3f3f8ff88fd0701b...67b4eb7068f8b100dd64f20784e56e8b838ad979).

So my only option is to assume this a bug in Biomes O' Plenty to be solved, so that Nether biomes will correctly generate when TerraForged is present.

**Comment by Forstride** [comment]
This is not a "bug," and the solution they gave you is the only one available for now.  The way world types work in vanilla now doesn't allow us to just freely use our Nether override.  Additionally, the Nether is not set up to easily allow additional biomes to be added.  We completely change how biomes generate in the Nether, and that's not really something other mods can easily adapt to without adding their own way of handling it.

**Comment by Won-Ton** [comment]
Hi.

The way TerraForged works is it gives users an option to choose the nether/end generator either from vanilla or from any of the other registered world-types (sunch as bop's), via our config gui.

We're very hands-off when it comes to nether/end generation because there are a bunch of mods that offer generators for it already and it's not the focus of our mod. We just delegate to whichever one the user wants to handle it. The logical default is vanilla's.

----

The issue that this person is reporting (and misrepresenting) is that they didn't understand how to make that selection when setting up on a server. Our wiki covers the steps for that, which is what we told them. I don't know why they have brought it to you in this manner after we explained all this :/

**Comment by MarioSMB** [comment]
I'd like to conclude this topic by stating that the wiki is misleading, documenting the preset steps as optional with no mention of special requirements for the Nether biomes (and definitely not stating that it's required on servers), I can guarantee many admins are going through this and have no community portal to reach out on. Hence making an issue on the subject, to which I received vague responses and had the thread locked. My hope was to help avoid this happening to others in the future, maybe this information will be enough for that, as I see no changes being made on any end. 

I have since learned how to manually modify the generator using NBTExplorerer, so the issue is "solved" for me. I apologise for bringing this to the Biomes O' Plenty tracker.  

Thank you to the team here for clarifying that it is an issue with the vanilla game, rather than modded environments leading to this workaround being necessary.
