### ISSUE TITLE
Error biomesoplenty requires Minecraft 1.13 or above

### ISSUE THREAD

**Issue by Kuraiko55** [Glitchfiend/BiomesOPlenty#1813]
**## Bug Report**
Starting Minecraft in version 1.12.2 with forge 14.23.5.2584 (no other mods installed) produces this error:
<img width="428" alt="86_javaw_2021-03-01_16-57-09" src="https://user-images.githubusercontent.com/56200847/109524025-49726a80-7ab0-11eb-9936-c20cd2a95cb6.png">
On curseforge however, it reads as if the mod should work for 1.12:
"For 1.12.2 and below, set level-type in server.properties to BIOMESOP."

**### How can the crash be reproduced?**
Start Minecraft in version 1.12.2 with forge 14.23.5.2584 and BiomesOPlenty-1.16.4-13.0.0.431-universal installed.
Also tried other mod versions which results in the same error.

**### Crash Report and Logs**
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/6062888/latest.log)

**### Mod Version**
BiomesOPlenty-1.16.4-13.0.0.431-universal

**Comment by Forstride** [comment]
You're trying to use the 1.16.4 version on 1.12.2...

**Comment by Kuraiko55** [comment]
> You're trying to use the 1.16.4 version on 1.12.2...

Alright. You answer at least pushed me in the right direction.
Never found a mod on curseforge.com that had so many versions that the "View all" button was available. Or I rather didn't need it.

No need to be rude though :/

**Comment by Forstride** [comment]
How the fuck was that rude lmao

Biomes O' Plenty has been around for 8+ years, and since 2014 on CurseForge specifically.  We also rarely skip versions like most modders, so there's pretty much going to be some release available for every version, which kind of adds up after a while.  Yes, their website has a shitty layout and only lists the 3 latest versions on the sidebar, but it's also kind of your fault for downloading a completely different version and not reading it properly.
