### ISSUE TITLE
It is impossible to enter the world a second time

### ISSUE THREAD

**Issue by kellixon** [Glitchfiend/BiomesOPlenty#1843]
- Minecraft: 1.16.5
- Forge: 36.1.13
- Biome O Plenty: 13.1.0.457
- plus other 251 mods
Unable to enter the world a second time in the world, biome generator error. Without the BOP mod, I can log in as many times as I want.
Full log (one game and it is impossible to enter more) - https://gist.github.com/kellixon/f7c63bf4e4d03a36bb95356a7b8e47a6

Full log (good game without BOP) - https://gist.github.com/kellixon/061538eca371d7638f5e2bb989892c68

**Comment by Forstride** [comment]
This log doesn't really show anything useful.  There's not a complete indication that this is caused by Biomes O' Plenty, and with 251 other mods, that'd be impossible to determine.  You're gonna have to start with ONLY Biomes O' Plenty, and slowly add mods from there to determine what's causing the conflict.

Also on a side note, I'm not sure why you have OptiFine *and* OptiForge.  The latter only exists as an alternative when OptiFine isn't updated with Forge support when a new MC version releases.

**Comment by TheSaikos** [comment]
for me optifine was always the cause of the problem, without it it worked for me
