### ISSUE TITLE
Incomplete set of Tags received

### ISSUE THREAD

**Issue by leninkster** [Glitchfiend/BiomesOPlenty#1899]
## Bug Report

Installed new Forge 1.17.1 server.   Installing mods one at a time.  Biomes O Plenty mod added and we get the error</br>

![image](https://user-images.githubusercontent.com/9325780/131005343-b8e7085c-4e98-41a4-b19d-8ebf58f8878e.png)

### How can the crash be reproduced?

Error is repeatable</br>

### Crash Report and Logs

[debug.log](https://github.com/Glitchfiend/BiomesOPlenty/files/7061501/debug.log)
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/7061502/latest.log)
</br>

### Mod Version
Mod version (both client and server) 1.17.1-14.0.0.38</br>

server.properties

[server.properties.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/7061512/server.properties.txt)

**Comment by JustinTheBob** [comment]
Worth noting on my server I am using BOP, BYG, and Better End.

**Comment by NotKate** [comment]
I am also having this issue. I have made sure the mod list on the server and client are the same, going so far as to make BOP the ONLY mod on both. It works in singleplayer and on a server hosted on the same machine, but not on a dedicated server I'm paying for. 

Attempting to connect to the server with BOP in the mods folder gives the "incomplete set of tags" error. Connecting works as expected without BOP. 

mod version: Biomes O' Plenty 1.17.1-14.0.0.36
forge version: 1.17.1-37.0.108
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/7529216/latest.log)

I imagine this line in the log is relevant somehow? Leninkster has the exact same thing. 

> [11:03:40] [Render thread/WARN]: Incomplete server tags, disconnecting. Missing: {ResourceKey[minecraft:root / minecraft:fluid]=[biomesoplenty:blood], ResourceKey[minecraft:root / minecraft:block]=[biomesoplenty:flesh]}

**Comment by NotKate** [comment]
I actually just solved the problem myself accidentally. It's related to improperly installing Forge, as described on this stack exchange post: https://gaming.stackexchange.com/questions/208231/i-cant-place-modded-blocks-on-my-minecraft-server

For posterity: other mods that don't give the "incomplete set of tags" error APPEAR to work in that you can connect to the server and they show up in the creative inventory, but no modded items can be spawned at all. It's 100% user error and not a BOP problem.

**Comment by Tsoccerguy3** [comment]
Happening in 1.18.1 

This is Bad coding . Instead of doing a server check , BOP attempts to load TAGS from variations of Vanilla , Bukkit , Spigot and Paper etc. ... and of coarse crash.  Most Forge mods will check and handle the exception and disable the mod if there is  nothing to do . Since BOP is mainly a custom world generator , it only performs in a Forge only environment . Forge sends extra tags that Vanilla , Bukkit , Spigot , Paper are not going to understand . 
Some Forge mods that handle graphic , sound and other aspects of Minecraft , handle the tags on a variety of server types . examples , Optifine , Sound Physics , Dynamic sounds , custom player models and anything that enhances the player experience , client side.

Ways to handle mods like BOP and its dependencies .

Create Forge instances for different situations , The problem is that a player may like to play on a variety of servers and need a instance for each server or situation . Disc Space issue.

Use an enhanced game launcher like MultiMC and just dump all your mods into a directory and create launch lists . This avoids having dozens of the same mod scattered across multiple directories.
or 
Lastly , BOP and its dependencies / add-ons , code and handle the correct server checks and disable itself if its not needed , example , like connecting to a Paper server . If a player is using Mojangs launcher , this eliminates the need for swapping out the mod when not needed or making a new instance .

I personally like MultiMMC ,

**Comment by JTBU** [comment]
I have the same problem. downloaded the server for a pre-made modpack and i get the incomplete set of tags. Sinse I am using a pre-made modpack I would believe it is not something wrong with. Any other things I could check?

**Comment by Forstride** [comment]
This will only ever happen if you are connecting to a server that doesn't have BOP installed.  And there's seriously no reason to be running an instance of Minecraft with BOP/other mods installed if you aren't playing on a server that has them installed.
