### ISSUE TITLE
Cold Desert causing lag death of server

### ISSUE THREAD

**Issue by Bobmcooper** [Glitchfiend/BiomesOPlenty#2007]
### What's the issue you encountered?

There is an area of my server (I don't know if it's relevant, but it is a cold desert) that is suffering a lag death whenever someone sets foot within it. The error is "a single tick took over 60 seconds". Sometimes, I get some warning exploring the boundaries of it in the form of detectable but non-fatal lag, and when I am able to note it, I'm usually able to "run away" from the gravel fields, and usually to a higher elevation, and prevent the crash. Other times, it's pretty sudden. 

Is there any known issue or concern with cold deserts, or some other potential on ground or underground structure, that could account for or be corrected in some manner? Right now, my best solution is going to be painfully working my way around the borders of the dead zone marking it with Cherry signs and eventually fencing it off entirely.

### How can the issue be reproduced?

Any time I walk into the gravel fields of a certain Cold Desert on my server.

### Logs

A single tick took over 60 seconds

### Mod Version

16.0.0.109

**Comment by annelidCerebellum** [comment]
I've experienced this when encountering a cold desert biome as well (though thankfully the server didn't outright crash), and I think it's likely at its core the same issue as described in [this bug report](https://github.com/Glitchfiend/BiomesOPlenty/issues/1975)  from February. It seems that the gravel in a cold desert biome, for whatever reason, updates when it's first generated and loaded by a player so that unsupported blocks convert to falling block entities which, when it happens to hundreds or thousands of blocks at once, can cause massive lag spikes. By contrast, of course, unsupported sand and gravel blocks in vanilla generation just stay that way until they receive a block update from an external source (usually a player digging at them or placing a block in contact with one of them).

**Comment by Bobmcooper** [comment]
Ok...so we've got the symptom sorted out...what's the cure?  Nudge my way into the zone one chunk at a time until it lags, freeze, stay put for 5 minutes until the entities decay, repeat, and pray I don't cause the lag-death of the server?

**Comment by annelidCerebellum** [comment]
Without changes being made to the mod itself to resolve the issue, yes, that's your best bet. That or upgrade the server itself so it's beefy enough that it at least just lags rather than outright crashing, but I don't think you want to have to do that.

**Comment by Adubbz** [comment]
This has already been resolved in the latest version of the mod.

**Comment by Bobmcooper** [comment]
If I install the updated version, will this fix the existing Cold Desert of Death Doom, or just prevent future-generated deserts from doing the same thing?

**Comment by Forstride** [comment]
All it does is replace the filler block with stone instead of gravel, so that the gravel on top won't fall.  So no, it will only affect newly generated Cold Deserts.

**Comment by BlackAures1** [comment]
This is the worst biome ever. I regularly forget to disable this crap in modpack on 1.18. and then the only way to escape is to make the lowest drawing distance.  Terrible.
