### ISSUE TITLE
Changes to Dead Branches

### ISSUE THREAD

**Issue by zackeroni9** [Glitchfiend/BiomesOPlenty#2050]
### Overview

I would like for Dead Branches to: 1.) at the very least have the ability to be placed on any log type 2.) have some method of renewability, likely being dropped from Dead Leaves.

### Why would this feature be useful?

Dead Branches would be more useful for adding detail to builds, custom trees, and for other building stuff. Currently they are really difficult to use in survival due to their rarity (only spawning on naturally generating Dead Trees, with only a few stacks per biome) as well as their strict placing conditions(only being able to be placed on Dead Logs. (It is more than likely possible to make a DataPack that can achieve this same functionality, but creating custom DataPacks always feels cheaty and unfaithful to the mod.)

**Comment by Forstride** [comment]
I'm not going to make them placeable on every log type without adding separate branches that match them, and I have no plans to do that seeing as they wouldn't be used at all.  As for the other thing, like you said you could just make a datapack for that.  We're not going to add/accommodate every suggestion that comes our way, so that's where datapacks come in.  It's not really "cheating" when you're already modifying the game as it is.
