### ISSUE TITLE
Hot tourist attraction does not include new biomes

### ISSUE THREAD

**Issue by Aceplante** [Glitchfiend/BiomesOPlenty#2106]
### What's the issue you encountered?

Title

### How can the issue be reproduced?

travel to new biomes
nothing
travel to vanilla biomes
get the achievement

### Mod Version

1.18.2

**Comment by Forstride** [comment]
Replacing vanilla advancements is definitely not something we want to do.  Even then, I'm not sure why you'd want the advancement to be *harder* instead of only requiring the vanilla Nether biomes lol

**Comment by Aceplante** [comment]
The point is to include all nether biomes, and if you add new ones, the achievement should include those

**Comment by Forstride** [comment]
Ok, and then if you use another mod that adds even more Nether biomes, their biomes won't be included...Or if they also have their own replacement for the vanilla advancement, one mod's replacement will end up overwriting the other (Although none even do this to begin with, because it's a dumb idea).
