### ISSUE TITLE
Replace oak leaves in bramble features with a dedicated leaf type

### ISSUE THREAD

**Issue by saltyseadoggo** [Glitchfiend/BiomesOPlenty#2108]
### Overview

Replace the oak leaves in the bramble features with a new `Bramble Leaves` block that is identical to oak leaves, but doesn't drop oak saplings.

### Why would this feature be useful?

- Brambles are very much not oak trees, so Jade pointing out that their leaves are oak leaves, and being able to get oak saplings from them, is very odd to me. I feel like it shouldn't be possible to obtain an overworld sapling type from an entirely unrelated plant in the Nether.
- Likewise, looking at brambles and seeing that their leaves are oak leaves makes the feature feel a little unpolished, like a worldgen datapack that has to reuse vanilla blocks instead of a mod. Giving them their own leaves would make the bramble features feel more polished.
- This would also pose an opportunity to make these bramble leaves see brambles as their "logs" and decay when the brambles are removed, just as one expects leaves to do in Minecraft. The current oak leaves are set to `persistent` and do not decay.

**Comment by Forstride** [comment]
![2023-06-20_02 31 51](https://github.com/Glitchfiend/BiomesOPlenty/assets/1512908/be834488-b33a-4da4-941f-d18c1eb4f2bb)

I didn't really want to just add another traditional leaf block solely to replace the oak leaves, so these are unique directional leaves, which is also nice since bramble will only connect to the leaf that's actually attached to it now

**Comment by saltyseadoggo** [comment]
Oooh! I really like the look of those, quite a glow-up! Good job~
