### ISSUE TITLE
Game crashes on attempting to generate Tundra Biome

### ISSUE THREAD

**Issue by RoseOfTheRaven** [Glitchfiend/BiomesOPlenty#2109]
### What's the issue you encountered?

When creating a new world in Singleplayer the game would crash during world generation. I got an exit code -1 and `The game crashed whilst exception generating new chunk
Error: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / biomesoplenty:tundra]=net.minecraft.world.level.biome.Biome@2051728b}]`

### How can the issue be reproduced?

Anytime creating a new world. Fixed by disabling Tundra generation in the BoP config file.

### Logs

https://gist.github.com/RoseOfTheRaven/031c19e9c92a095172fa819c0b12fc12

### Mod Version

1.20.1-18.0.0.573

### Additional information

I am using mods but this should be the only mod affecting biomes/terrain generation.

**Comment by Forstride** [comment]
Likely another mod adding features to multiple biomes incorrectly.  There's no way to determine what mod it actually is though, since the whole feature order cycle thing is garbage.  But, the issue definitely doesn't occur with BOP alone, and the only vanilla features the Tundra has are all in the same order that they're in in vanilla biomes.  And obviously none of our own features would be causing it.
