### ISSUE TITLE
[1.19.2] Maple Trees spawn without enough logs to support the leaves

### ISSUE THREAD

**Issue by Reshy** [Glitchfiend/BiomesOPlenty#2131]
### What's the issue you encountered?

The maple trees seem to be lacking proper coverage for their leaves, leading to mass leaf decay when the biome gets generated.
![image](https://github.com/Glitchfiend/BiomesOPlenty/assets/2096384/4582dd35-75ab-42c3-93b4-75f1a4228a5d)

### How can the issue be reproduced?

Generate a Maple Woods biome

### Mod Version

 BiomesOPlenty-1.19.2-17.1.1.162.jar

**Comment by Forstride** [comment]
I'm not sure why there are maple leaves on the ground, but it seems like you have some other mod adding/changing things using our blocks, so it could very well be because of that.  Also the tree generation should be the exact same as vanilla's big tree, and I've never seen any issue with it myself, so...

EDIT: Just tried it and yeah, not seeing leaves decay at all with the tick speed set to 1000.

**Comment by Reshy** [comment]
Strange, I tested the mods I suspect might be causing the issue (Fast Leaf Decay, Immersive Weathering, and Every Compat) and couldn't replicate it.  Must be some sort of other conflict somewhere I'm not catching, all I know is it's causing a lot of the leaves to be marked as distance 7, which then start decaying.

**Comment by Forstride** [comment]
I'd suggest starting with *just* BOP and going from there.

**Comment by Forstride** [comment]
Closed due to not being able to replicate the issue

**Comment by Reshy** [comment]
I figured it out, it was a mistake that can happen with MCcreator mods.

> I had a non existent block in the leaves tag file which nullified it and broke BOP’s leaves tag file
