### ISSUE TITLE
BOP and Optifine

### ISSUE THREAD

**Issue by iplayminecraft4aliving** [Glitchfiend/BiomesOPlenty#2140]
### What's the issue you encountered?

I've installed both BOP and Optifine. For some reason when trying to launch Minecraft it crashes. Based off of my knowledge, Optifine is somehow interfering with BOP. Not sure if this is Optifine's or BOP's issue. 

### How can the issue be reproduced?

Added both BOP and Optifine to the mods folder and then launched Minecraft. 

### Logs

https://gist.github.com/iplayminecraft4aliving/f76e1735b4db85f909bf5558e7ab89ac

### Mod Version

18.0.0.597

**Comment by Adubbz** [comment]
Though for whatever reason Biomes O’ Plenty is listed at the start of your log, if you look later on it’s actually caused by a Mixin failing to apply from forge-immediatelyfast-forge.mixins.json. Specifically: `Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method renderTrim in forge-immediatelyfast-forge.mixins.json:core.MixinArmorFeatureRenderer was not located in the target class net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer. Using refmap forge-forge-forge-refmap.json `. You’ll need to raise this with the developers of immediately fast, no code from BOP appears to actually be being called so there isn’t anything we can fix here.
