### ISSUE TITLE
Better liquid mechanics

### ISSUE THREAD

**Issue by rafaelkai** [Glitchfiend/BiomesOPlenty#2158]
### Overview

Liquids present in BoP lack proper visual overlays like lava, like blood among others. These liquids should also slow down the player and act more like a liquid physics-wise.

### Why would this feature be useful?

Consistency with vanilla game overall.

**Comment by rafaelkai** [comment]
EDIT: Seems they do have visual overlays but have some incompatibilities with Shaders/Oculus. It would be nice if a custom sound could be added when swimming in blood.

**Comment by Forstride** [comment]
Swimming sounds aren't really feasible to add since that's done entirely within entities and it only checks for swimming in water.  But I can give flowing blood a sound at least (Although probably just gonna use either the flowing water or lava sound for it since finding a proper royalty-free sound for that would be a pain)

And yes the fog is known to have issues with shaders, but that's entirely on them.  The blood fog is done the way every other fluid does it, and if some shaders completely replace water/lava fog with their own, but don't account for modded fluids, there's nothing we can do about it.
