### ISSUE TITLE
no texture blocks in the end 

### ISSUE THREAD

**Issue by xavierkessen** [Glitchfiend/BiomesOPlenty#2168]
### What's the issue you encountered?

hello i installed this mod everything works fine but when i come to the end world it gives me textures without a texture like those pink black blocks and it craches people also holes in the map 

### How can the issue be reproduced?

.

### Mod Version

1.20.4

**Comment by Forstride** [comment]
The blocks with the black/magenta textures are entirely intentional.  The biome is called the End Corruption for a reason.

As for crashing, we can't do anything without an actual crash report, but certain issues with the Anomaly blocks have been fixed recently, so make sure you're using the latest version of the mod.
