### ISSUE TITLE
Crash. Your mod was directly mentioned 

### ISSUE THREAD

**Issue by ArrowFX** [Glitchfiend/BiomesOPlenty#2173]
### What's the issue you encountered?

I used waystones to tp to a distant village, and I crashed after about 1-2 minutes.

Crash log: https://paste.ee/p/NeOLi

### How can the issue be reproduced?

Yes. If I launch the game a use a waystone to any distant location I will crash in about 1-2 minutes

### Logs

https://paste.ee/p/NNJNU

### Mod Version

18.0.0.598

**Comment by Adubbz** [comment]
The biomes supposedly implicated in feature order cycle related crashes are almost always inaccurate. Furthermore, feature order cycles occur due to ANY features being in the wrong order relative to Vanilla, including those added by other mods to our biomes. Given that these crashes do not occur with BOP on its own, nor to my knowledge with just BOP and Terralith (the other mod which is claimed to be implicated in your log), it's almost certainly the result of the features added by another mod to our biomes. There's nothing we can do about that, and you'll have to figure out which mod that is.
