### ISSUE TITLE
Redwood Textures are broken

### ISSUE THREAD

**Issue by autumnly24** [Glitchfiend/BiomesOPlenty#2191]
### What's the issue you encountered?

I don't know what happened, but redwood textures have recently become this extremely unrealistic, ugly, and saturated red instead of the nice orange colour they used to be. I have no reason why this would purposely be put in, so I assume it's a bug.
![2024-03-13_14 44 00](https://github.com/Glitchfiend/BiomesOPlenty/assets/83057109/9fa6eb98-96e5-4b89-ba40-77c4c67b0297)

### How can the issue be reproduced?

Install the Mod
Launch
Get Redwood

### Mod Version

18.0.0.592

**Comment by Forstride** [comment]
It looks like that because people liked the bright red color of our old Cherry wood, and this was the only way to really keep something like that without adding a new wood type solely for that purpose.  Plus the old Redwood color was a little too similar to Acacia, and I'd rather our woods have unique color palettes so that they're fun to use and people have a reason to seek them out.

Also unrealistic colors don't matter when vanilla doesn't adhere to that either.  Cherry wood isn't pastel pink in real life, but it's what most people would've expected/wanted for it in Minecraft.
