### ISSUE TITLE
Option for each woodset to use vanilla cherry woodset sounds

### ISSUE THREAD

**Issue by vico93** [Glitchfiend/BiomesOPlenty#2193]
### Overview

More a minor aesthetic request, but i personally feel that the cherry woodset (logs, planks, doors, trapdoors, fences, fence gates and other related blocks) sounds added in 1.20 far more pleasant to hear than the oak/dark oak/jungle/birch/spruce (that i will call the *"standard"* woodset) sounds. And, unfortunately, its very hard to replace the standard sounds with cherry ones in Resource Packs due to the differences between the sound files (cherry actually have more variants than the standard ones).

So, i suggest adding an optional boolean option, one for each woodset added by BoP, to use the cherry woodset sounds instead of the standard ones.

### Why would this feature be useful?

This would add another aesthetic customization option for BoP users, which can depending of the player taste, align more with modern Mojang's style than the standard sound set provide.

**Comment by Forstride** [comment]
I could probably change a few of our wood types to use it (Probably Maple, Jacaranda, and Magic wood), but I'm not adding an option for *all* of them to use it.  Especially because if more wood types are added to vanilla in the future and they have unique sound types (Or they just decide to give old woods new sounds), I'd probably want to spread them between some of our other wood types as well.

**Comment by vico93** [comment]
> I could probably change a few of our wood types to use it (Probably Maple, Jacaranda, and Magic wood), but I'm not adding an option for _all_ of them to use it. Especially because if more wood types are added to vanilla in the future and they have unique sound types (Or they just decide to give old woods new sounds), I'd probably want to spread them between some of our other wood types as well.

Roger that!
