### ISSUE TITLE
MANY Sculk caves

### ISSUE THREAD

**Issue by MrKirilchik** [Glitchfiend/BiomesOPlenty#2223]
### What's the issue you encountered?

I noticed that after installing the mod, a huge number of skulck caves began to be generated

### How can the issue be reproduced?

just fly in spectator mode underground

### Mod Version

21.0.0.3

**Comment by Forstride** [comment]
Unless you can provide definitive proof with a mapping tool or something across multiple worlds, I think you're just imagining things, because it's entirely possible to have a lot of sections of Deep Dark or Ancient Cities spawn very close to each other.

I mean we do add the Deep Dark to our TerraBlender regions, but it's done in the exact same way as vanilla, and it shouldn't double up on them or anything.  And if it's below a section of vanilla biomes, it definitely wouldn't have anything to do with BOP.
