### ISSUE TITLE
Black wolves in Ominous Woods

### ISSUE THREAD

**Issue by West8777** [Glitchfiend/BiomesOPlenty#2241]
### Overview

I found an Ominous Woods in my world and was surprised to see that the only wolves that spawn there are the standard Pale wolf. I think that they should be changed to the Black wolf to match the environment better.

### Why would this feature be useful?

The white coat of the Pale wolf stands out too much among the Ominous Woods' dark purple foliage, the Black wolf would blend in much better.

**Comment by Forstride** [comment]
They *do* spawn black wolves.  Some other mod might be overriding the wolf variant data files, because they're technically not extendable due to the way Mojang implemented it.  We just have custom tags that myself and a few other biome mod devs agreed to use, but any other mod could easily override it and mess that up.

**Comment by West8777** [comment]
I see, I am using CliffTree, that might be what's messing it up. Thank you!

**Comment by Forstride** [comment]
Looking at that mod, yes, they override the wolf variants and supply their own biome tags for them, whereas we override them and use tags under the 'c' namespace that myself and a Terralith dev agreed upon, and that other biome modders are aware of for when they eventually update.

I'd suggest reporting it to them and tell them to use the same tags we use: https://github.com/Glitchfiend/BiomesOPlenty/tree/1.21/common/src/main/resources/data/c/tags/worldgen/biome/has_wolf_variant
