### ISSUE TITLE
BoP worldgen selected by default maybe perhaps?

### ISSUE THREAD

**Issue by Roadcrosser** [Glitchfiend/BiomesOPlenty#410]
Because I can envision many people starting a new world without even changing the worldgen type.

Could also do it for servers.

**Comment by Max-Shen0** [comment]
For the client, you get a nice information screen telling you to use the custom worldgen. It only appears once, however.
Not sure if servers have a similar one-time message, but the client screen does say you have to use BIOMESOP on servers if you want the worldgen.

**Comment by Syndaryl** [comment]
I'd like it, because I simply don't use any other world-gen type so it's a small irritation to have to set it every single time. I know to do it, I always remember to do it, but it's just that one-more-thing factor that's just a little irritating.

But only a little irritating - I can't be bothered to figure out how to change it myself, for example.

**Comment by evenas98** [comment]
i would like this

**Comment by Roadcrosser** [comment]
I actually only posted this just for posterity.

Adubbz had already agreed to my suggestion beforehand, and this is just to remind him if/when he ever goes over the issues page.

**Comment by Adubbz** [comment]
Alright, i've added a config option for it, however, it is only client side only for the time being and it defaults to off. I'll make it default to on once all the biomes have been added again.
