### ISSUE TITLE
BoP + Mystcraft = performance issue with new worlds

### ISSUE THREAD

**Issue by mSt3in** [Glitchfiend/BiomesOPlenty#443]
1.7.10; tried both build 1067 and 1164

When a new world is made, mystcraft does what ot calls "instability profiling."

BoP causes this profiling to take three times longer than it should, somtimes more than that, and on occasion causes an out of memory exception even on machines with very large amounts of ram.

https://github.com/XCompWiz/Mystcraft-Issues/issues/54

**Comment by XCompWiz** [comment]
Any progress on this?

**Comment by ajthemacboy** [comment]
Hello..? This is a big problem.

**Comment by Novocastrian** [comment]
Anyone still having this problem? I have the exact problem that mSt3in is having (BoP + Mystcraft Profiling = eventual client crash). Playing SSP hosted on my PC. 100% sure that BoP is causing the crash upon new world.

**Comment by ajthemacboy** [comment]
I don't have a crash in ssp, but I do have extreme lag on servers.

**Comment by XCompWiz** [comment]
Just for the record, anyone encountering this should try with latest Mystcraft and report back if it is fixed. There was a missed event which might have been causing other mods to leak.

**Comment by ajthemacboy** [comment]
@Adubbz, has this been fixed or are you just closing old issues? The latest version of Mystcraft never fixed the lag for me.

**Comment by Adubbz** [comment]
XComp mentioned that there was an issue in Mystcraft that has been fixed so I assumed this specific issue with 'instability profiling' and memory leaking was resolved. 

At the time this issue was made, the 1.8 update still needs work and that remains to this day. With this in mind, without a concrete 'WorldGenX is causing performance problems because of Y as shown by Z' it's a bit difficult for both us, and the kind people submitting pull requests to really do much about. Performance issues can originate from a variety of things, and it becomes even more difficult when it's an issue with another mod that is closed source which you have a limited understanding mechanically and technically of. 

That's not to say we have no role in any performance problems whatsoever, we're not perfect by any stretch of the imagination. However, the issue needs to be a bit more specific to warrant looking at.

**Comment by Bogdan-G** [comment]
the call is not stability in the world: mod mystcraft + bop + ubc, and and throw with the generation of mods can be multiple, without generating large objects.

**Comment by ajthemacboy** [comment]
Your comment is very unclear @Bogdan-G, can you re-phrase? What is UBC?

I believe the issue is that somehow Mystcraft is somehow calling BOP when generating Mystcraft ages, causing Mystcraft ages to use both BOP and Mystcraft generation, doubling the lag. 

I never really understood why Mystcraft has to do this laggy "ore profiling" thing though. Other dimensions, like Twilight Forest, and every RFTools dimension, don't need to do this for ore generation. 

Why does Mystcraft?

**Comment by Bogdan-G** [comment]
@ajthemacboy an example of what events mystcrart the interaction causes a number of problems. It also interferes with the generation of generation of the world.
