### ISSUE TITLE
[Suggestion] Configs

### ISSUE THREAD

**Issue by Neodark7** [Glitchfiend/BiomesOPlenty#448]
Can you make a config to modify potions id and one to disable oregen ?

**Comment by Dream-Master** [comment]
Yes this would be great because I use Bop in a 1.710 pack and let Gretech spawning the ores.

**Comment by Prophious** [comment]
amethyst armor/tools config needed... imo 34 armor points for something that is only 70% as hard as diamond IRL should not be +70% of diamond... so i suggest that it gets nerfed to 17-19 armor points, or allow for server to set the armor points for modpack balance

**Comment by Taschenmogul** [comment]
As far as I know the BOP developers are aware of the lack of config options in BOP for 1.7.10.
If I am not mistaken though the amount of work needed to implement some of them is so great that they decided to rather not implement them in the 1.7.10 version but instead implement them in the 1.8.x version of BOP where they have the chance to program the mod from the ground up with regard to configurability.

Given that there still only seem to be a handful of mods for 1.8.x and that it may still take many months till even just a significant amount of the more known mods have upgraded to 1.8.x we will see if some BOP dev will decide to provide some more config options for the 1.7.10 version of the mod.
My top two of missing config options: The option to completely disable the registration of specific biomes and the option to specify weights for the generation of vanilla biomes.
I highly though that any of those config options will be provided for 1.7.10.

**Comment by Fickilty** [comment]
Actually. Nevermind config options. 34 points of armour needs to be nerfed HARD, because at /25/ points of armour, armour stops taking damage all together. More than that, the player stops taking damage as well.

**Comment by cheeserolls** [comment]
2 separate issues here.  Config options will be greatly increased in the 1.8 version.  Editing potion IDs is a good idea.  @Fickilty are you saying that if you're wearing Amethyst armour you're basically invincible?  That's a more serious bug.

**Comment by Fickilty** [comment]
Quite literally invincible. It might be a forge bug. My partner and I found a forge bug (fixed in the latest 1.8 version) where armour doesn't behave the way it should.

What the bug did: Damage resistance was based on armour durability not armour points.

Amethyst armour making the player invincible isn't really an issue at the moment though, as there's no current way to get ender amethysts without adding recipes for them/creative/commands.

When changing amethyst armour points, you might want to keep in mind other mods adding in armour as well. Because I know that with: amethyst helmet, diamond chestplate, diamond leggings, and metallurgy tartarite boots that "sweet" invincible spot of 25 armour points is reached.

Likewise with: amethyst helmet, IC2 composite vest, diamond leggings, diamond boots the player is rendered invincible.

For reference, amethyst helmets and boots, offer the /least/ amount of protection from the set, with other mods that invincible point is still reached.

I feel like I butchered my grammar a few times there. Sorry about that. It's nearly 3am.

**Comment by cheeserolls** [comment]
OK, so, the original question about configs is answered:  It will happen in the (coming soon) 1.8 version.

I've opened a new issue (https://github.com/Glitchfiend/BiomesOPlenty/issues/491) to continue the discussion of this amethyst armor invincibility issue.
