### ISSUE TITLE
Weird crag mountain generation

### ISSUE THREAD

**Issue by lhenrique03** [Glitchfiend/BiomesOPlenty#474]
I don't know if it's intended to be like that, but I found this crag biome, that for me looks very strange;
Screenshots: http://imgur.com/t0aj9xM,hUdP1YP#0 and http://imgur.com/t3b1DTk
BOP Version: 1.7.10-2.1.0.1067

**Comment by ate0ate** [comment]
I have noticed that nearly every crag I have encountered looks like this as well. It does seem odd.

**Comment by ajthemacboy** [comment]
I think it looks interesting. It would be nice if there was the (extremely requested) amplified option to make the entire world generate like this.

**Comment by Taschenmogul** [comment]
Hm. I looked at the first picture (actually also at the second one which though is so dark I can't see anything on it) and I didn't see anything weird about it.
Ok, giant floating rocks are a little uncommon even for the Crag biome, but appart from that it looks just like the Crag biome is supposed to look since at least BOP for Minecraft 1.6.4.

So may I ask what any of you consider weird or odd about the biome generation seen on picture 1?

**Comment by lhenrique03** [comment]
the floating rocks, I imagine that a crag biome like that should be a huge mountain, not some random rocks floating around

**Comment by Syndaryl** [comment]
The floating rocks is pretty typical Minecraft random terrain generation glitch, as far as I can tell, and a consequence of the combination of extreme steepness and some standard optimizations in chunk generation. I see that kind of scooping pretty regularly in eg. jade cliffs. 
I'm not sure how you could get rid of that without making chunk generation slower...

**Comment by cheeserolls** [comment]
@Syndaryl is correct - floating rocks are likely to happen with Minecraft's standard terrain generation whenever the scale setting is turned right up.  Would need to use a totally different approach to rule it out completely.  Floating rocks are fun, so we're calling it a 'feature' instead of a 'bug'.
