### ISSUE TITLE
[1.8.3] All saplings grow oak trees

### ISSUE THREAD

**Issue by Subsuperhuman** [Glitchfiend/BiomesOPlenty#517]
When growing a BOP sapling in the 1.8 version, with bonemeal or without, the result is always an oak tree. This happens both in vanilla biomes and in BOP biomes.

**Comment by jadenPete** [comment]
I have the same issue.

**Comment by tp-peacock** [comment]
I have also been experiencing this.

**Comment by fruitydragon** [comment]
I have the same issue its really annoying, im playing on 1.7.10 now because it works fine there  /:

**Comment by cheeserolls** [comment]
Sorry guys - 1.8 is not finished yet.  We haven't finished programming all the tree stuff.  Should be ready in about a month.

**Comment by tp-peacock** [comment]
Thanks for the update, looking forward to it!

**Comment by jadenPete** [comment]
Ok, thanks!

**Comment by Subsuperhuman** [comment]
Cheers for the response. Looking forward to seeing it.

**Comment by fruitydragon** [comment]
So are the trees for someone already normal? Because mine are not :(

**Comment by Shadow43** [comment]
It's doing the same thing for me on 1.8.0 as well.

**Comment by fruitydragon** [comment]
Well, the modmaker could atleast say that it is taking longer or that hes
busy or something, ive been waiting already for months and he said it would
be done in a month or so ;[
Op 14 jan. 2016 19:05 schreef "Shadow43" <notifications@github.com>:

**Comment by Shadow43** [comment]
Well, fruitydragon he **did** say that it **should** be done in a month or so.

cheeserolls commented on Sep 8, 2015
Sorry guys - 1.8 is not finished yet. We haven't finished programming all the tree stuff. Should be ready in about a month.

**Comment by Adubbz** [comment]
This has already been addressed in 1.8.9 for all of the saplings that are used within the biomes currently added... Yes, the month deadline didn't happen, both cheeserolls and I had our own things to deal with that we didn't think would be an issue.

**Comment by Shadow43** [comment]
I see. Well, I can't use 1.8.9 because almost all of the mods I'm currently using on my server don't work with 1.8.9.
And I can't get the correct logs without going into creative mode. I bet that is the case with the others that can't grow the right trees.

**Comment by fruitydragon** [comment]
Hey it is nice that it updated but i can't play 1.8.9 because my other mods
and server don't support it when it is another version, will the 1.8.3
version trees be fixed?
Op 8 sep. 2015 09:23 schreef "Daniel Howard" <notifications@github.com>:

**Comment by fruitydragon** [comment]
Anything?
Op 17 jan. 2016 13:05 schreef "Alex Ellen" <alexellensmith@gmail.com>:

**Comment by Adubbz** [comment]
I don't think it's worthwhile backporting to 1.8, making the same changes for multiple minor versions of the game just becomes tiresome. For other mod developers, 1.8->1.8.9 is a very small update and infact, if they were already updated to 1.8.8 then it should also work on 1.8.9. Because of this, most mods i'm aware of are already on 1.8.9 (e.g. Blood Magic, ComputerCraft, Buildcraft, Thaumcraft, TConstruct etc. etc.).

**Comment by fruitydragon** [comment]
Yes, but my server doesn't support it :(
I have to abondon one of my fav mods then, too bad._.
Op 22 jan. 2016 23:47 schreef "Adubbz" <notifications@github.com>:

**Comment by Shadow43** [comment]
I see. I have at least 29 mods and all most all of them are not updated to 1.8.9 and are still 1.8, and thus won't WORK for 1.8.9 

Not sure what to do.....

**Comment by Adubbz** [comment]
I understand it's not ideal, I really do, but here's where it's at. Updates are as much of a pain for us as it is you guys, and what that means is that people either put off updating for a very long time, or they do it straight away. We took the second option because we still don't have a stable build out for any version of 1.8.x (although we're getting close now) and when we get that build out, we don't want it to be outdated the moment it comes out the door. But many people choose the first option, and that's fine, everyone has their own choices, but what that means is others have to pick up their slack by backporting. As the name implies, backporting is even more painful than updating because, in its nature, its taking a step back and discarding all of the work put towards moving forward. Backporting keeps us in a perpetual loop where we keep having to stack changes upon changes to keep every version of the mod up to date. It's not always as simple as 'copy and paste x to branch y'. So, it's something to be avoided if at all possible. For the reasons i've mentioned above, and in my post earlier, I think giving backporting a miss for 1.8 is not unreasonable.

If this were 1.8.x->1.9 this may be an entirely different story, but in this specific scenario, I don't at all think it's unfair to shift the workload onto those who haven't updated already to make a change once, rather than us having to make the same changes to backport constantly, reducing the time that could otherwise be spent on getting the mod into a stable state.
