### ISSUE TITLE
Crash... No idea from what I do not understand this crash

### ISSUE THREAD

**Issue by DoughnutDev** [Glitchfiend/BiomesOPlenty#519]
http://pastebin.com/TYdhyPct

**Comment by Tomson124** [comment]
Same crash on my server.

**Comment by DoughnutDev** [comment]
So I went through with MCEdit and removed all the sand in which it said it was ticking falling sand, and I have not had the crash sense.

**Comment by DoughnutDev** [comment]
Still happening even with new world

**Comment by Aubron** [comment]
This error has occurred on our server (AlienMC) now as well.

http://pastebin.com/AF3KFd2k

Appears to be BoP Coral and other decoration blocks in oceans interacting with falling sand.

We have implemented a temporary workaround via forge's "B:removeErroringEntities" and "B:removeErroringTileEntities" settings in forge.cfg, but these are highly warned against settings that do not fix the problem, but instead remove the blocks instead of crashing the server.

**Comment by DoughnutDev** [comment]
This has been fixed in latest version of BOP it was a bug with Matter
Overdrive black holes.
