### ISSUE TITLE
Request - Needs better 1.7.10 Support

### ISSUE THREAD

**Issue by DPxKnightxZero** [Glitchfiend/BiomesOPlenty#551]
Alright I love this mod but 1.8 is a bust the 1.8.x is garbage can you please fix the weird lag spikes in 1.7.10 I know maybe you think your not being cutting edge well according to most devs ... even forge is waiting for 1.9 due to 1.8 basically being a flop update. Anyways 1.7.10 is a great and mostly stable release about 98% stable. The forge release brings it to 100% stable so as you can 1.8 is a waste of your time and mine. It makes more sense to start repairs on 1.7.10

**Comment by Adubbz** [comment]
This is most certainly not open for discussion. 1.8 is by no means a flop, but many other developers have chosen to remain on 1.7 for the time being for their own reasons. I respect their decision, as you should respect ours.

 It's not about some desire to be perceived as 'cutting edge', it's about wanting to move forward, and benefit from the changes Mojang has made performance-wise, code wise and feature wise. Forge 1.8 is perfectly stable, as i'm sure 1.7 is also.

Let's also not use made up statistics here for 'stability', the only real statistic you can use is number of bugs which even then, is highly inaccurate as it only shows the number of bugs which have been *found*. There's also numerous aspects contributing to stability, including Minecraft itself, Forge as well as the mods themselves. 

Development of BoP occurs independently of other mods. BoP won't be held back because some people or modders wish to stick with 1.7. I've been incredibly busy as of late but when I do get time, I don't intend on working on something that's not really going to help the mod move forward. There is no point rewriting the 1.7 version then doing the same again for 1.8.
