### ISSUE TITLE
[1.7.10] Custom biomes generation problems

### ISSUE THREAD

**Issue by Dragonisser** [Glitchfiend/BiomesOPlenty#565]
BOP seems to use the biomes of other mods and generate them in the normal even though some of them shouldnt be generated there. Config doesnt help and an api to disable them isnt provided.

http://www.minecraftforge.net/forum/index.php/topic,35480.0.html

**Comment by Adubbz** [comment]
"There are also no id conflicts which normally would cause such a thing." Your code seems to suggest otherwise (conflicting with yourself). https://github.com/Dragonisser/CobaltMod/blob/master/src/main/java/cobaltmod/main/CMMain.java#L184

BoP only adds biomes from other mods that have been added to BiomeManager. If they have not been added to BiomeManager, then you can guarantee that there's a conflict somewhere. Your biomes do not show up in our generation lists (I added debug code to check) thereby suggesting that there is at least one or more conflicts (the above was only one I found, there may be more)

**Comment by Dragonisser** [comment]
I cant thank you enough. This was such a small mistake and with the rush and fear of not finding it, it was only that in the end...

Anyway thanks a lot.
