### ISSUE TITLE
[1.7.10] Wetland COLD/WARM change

### ISSUE THREAD

**Issue by mmelvin0** [Glitchfiend/BiomesOPlenty#602]
After 1.7.10-2.1.0.1067, the Wetland biome was changed from COLD to WARM.This means that with the exact same config and seed, BoP now generates entirely different terrain. Because of this, I can't update my server past that version.

I have confirmed that changing that back in the latest 1.7.10 code causes BoP to generate the same terrain as before with no other changes. Note, however, I do have most BoP biomes disabled.

If you want, I've got a pull request that changes this back. I figure if this change is acceptable, it's easier than me maintaining a custom fork.

**Comment by Adubbz** [comment]
No objections here, this specific change probably should've been left for 1.8 anyways

**Comment by mmelvin0** [comment]
Glad to hear, thanks for the quick response. Two notes:

1) Your changelog credits me as Mike Rawlinson, which is a little odd, because that's not me. I barely understand Gradle, so I'm not sure if that's got anything to do with you. No big deal, just figured I'd point it out.

2) There were a few other biomes changed in that same commit, but I don't have any of them enabled. I can submit a PR to change them back too if you'd like.

**Comment by Adubbz** [comment]
1. We use Forge's changelog script to generate our changelogs, however I believe it goes off of part the email associated with the commit. Git has a somewhat annoying tendancy of requiring an email, although Github does provide an option of masking your email with a noreply one. The same thing happens for everyone except for those who have an account of the Forge Jenkins I believe, which is why it doesn't happen with myself, cpw, Lex etc.

2. If they're changes which only impact decoration as opposed to generation I think it should be fine. They generally tend to not cause many issues from what i've seen. If they do mess up seeds then you're welcome to make another PR by all means.
