### ISSUE TITLE
Nether biomes

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/BiomesOPlenty#606]
Nether biomes:
- Boneyard
- Fungi Forest
- Phantasmagoric Inferno
- Polar Chasm
- Undergarden
- Visceral Heap

**Comment by MauveCloud** [comment]
I'm not sure about Glistening Caverns, but I'm fairly sure Fungi Forest was an Overworld biome in the 1.7.10 version of BoP, rather than a Nether biome, so I'm puzzled that it is listed here.  Should there be a separate bug for tracking Overworld biomes that have yet to be re-added? (and if there are any that are deliberately not going to be re-added?)

**Comment by Hypsellis** [comment]
I can suggest you to take a look on this mod if it can help you with nether biomes. ;)
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279248-the-nether-expansion-v0-3

**Comment by MauveCloud** [comment]
@Hypsellis you realize the first post of that thread hasn't been updated since 2013, right?  Also, the wiki and download links are broken, and the mod apparently required Risugami's modloader, which means it was for 1.5.2 or older.

Linking to the re-write might be more helpful: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2654036-the-nether-expansion

The download links in that thread don't work for me either, but at least there's a GitHub link on the second page of that thread.

**Comment by FoxZOolm** [comment]
1.10.2-5.0.0.2109 seen dont worldgen nether biomes...

**Comment by Adubbz** [comment]
... That's why the issue is still open...

**Comment by Hypsellis** [comment]
They will necessarily add it one day or another, they just haven't more the time and desire to do it now. Anyway you can still help by giving some suggestions or helping for the code. ;)

**Comment by bartoxe** [comment]
Why some really cool biomes e.g Fungi Forest, Dunes or Jade Cliffs are removed? I miss them because they were really cool. Here's some screens.
![2017-04-12_20 05 43](https://cloud.githubusercontent.com/assets/27370277/24973955/f41a745e-1fc0-11e7-9828-c123cbb7388f.png)
![2017-04-12_20 01 32](https://cloud.githubusercontent.com/assets/27370277/24973964/fc16919c-1fc0-11e7-957c-33464bc051d1.png)
![2017-04-12_20 21 44](https://cloud.githubusercontent.com/assets/27370277/24974004/21e910de-1fc1-11e7-8c11-41f15de96d4d.png)
![2017-04-12_20 05 07](https://cloud.githubusercontent.com/assets/27370277/24974010/2a8213a8-1fc1-11e7-90a8-b4aedff23f2d.png)
![2017-04-12_20 02 55](https://cloud.githubusercontent.com/assets/27370277/24974043/4491642e-1fc1-11e7-92a8-292881b41c21.png)



Some old versions of biomes
![2017-04-12_20 16 55](https://cloud.githubusercontent.com/assets/27370277/24973988/15af1ab6-1fc1-11e7-84b3-53f69455f989.png)
![2017-04-12_20 18 00](https://cloud.githubusercontent.com/assets/27370277/24973994/188619ce-1fc1-11e7-9b92-dbf88382dff0.png)
![2017-04-12_20 02 09](https://cloud.githubusercontent.com/assets/27370277/24974026/39840f0a-1fc1-11e7-83df-652abe702225.png)

And villages...
![2017-04-12_20 04 33](https://cloud.githubusercontent.com/assets/27370277/24974021/3208a9d4-1fc1-11e7-976e-46d4b3e144f8.png)

It would be really cool if you re-add them. Thanks!

**Comment by Hypsellis** [comment]
Yeah it's right some biomes from the 1.7.10 version really misses.

**Comment by Hypsellis** [comment]
Any plans to backport it for 1.10.2 ?

**Comment by Adubbz** [comment]
The boneyard didn't really look good in its previous form. We tried using fossils and it just ended up being a chaotic mess, so we ultimately opted to ditch it. The same as always applies for backports, we won't be doing them, but people are welcome to submit a pull request.

**Comment by Hypsellis** [comment]
Oh I understand, but in this case why not just generate them sometimes as a rare in structures in any biomes and not in an standalone biome. Otherwise you could use CompatLayer for making BOP compatible with both 1.10.2 and 1.11.2

**Comment by Adubbz** [comment]
Ehh, maybe? I still don't personally think that look all that great. We'd prefer not to have any dependencies for BoP, aside from Forge and its libraries. It just makes life more difficult if any issues arise with it, and we'll get the blame. Additionally it makes me rather uncomfortable inflating another's download count on CurseForge as a result of BoP.

**Comment by Hypsellis** [comment]
Yeah I totally understand, I just give suggestions. I wanted to give another suggestion about polar chasm, you should add hot spring water lakes inside, it would be logic to find hot water in the nether. And maybe add too packed ice that would generate sometimes like the ice does. I could suggest the adding of ice and packed ice counterpart for hot spring water.

**Comment by xenowolff** [comment]
How do I make a pull request for this? I'm asking here because I have a server of about fifty players (all local friends and acquaintances) who about rioted on me when I told them 1.11 got updated with nether biomes and 1.10 didn't (our server is 1.10 currently, with about half our mods not updating to 1.11 any time soon.)
I apologize for my noobishness.

**Comment by Adubbz** [comment]
A pull request involves setting up a development environment and adapting/testing all of the changes made for 1.11 to 1.10, and then pushing your changes to Github. It's not as simple as pressing a button to simply add everything from 1.11 to the 1.10 branch, otherwise we'd do it automatically.

**Comment by xenowolff** [comment]
Then... I simply don't have the understanding to do that yet. Thank you for letting me know.
