### ISSUE TITLE
Unknown net.minecraftforge.common.chunkio.QueuedChunk - 1.7.10 Build 1640

### ISSUE THREAD

**Issue by enterprise12nx** [Glitchfiend/BiomesOPlenty#655]
I have been generating my world, and working with @Robotia on fixing bugs for Cauldron.

However, this issue arrised when i upgraded from an older version of Biomes o Plenty and made a fresh world.

It happens once or twice a day within 24 hours, im using ATG and other worldgen mods, but it seems to point that it is indeed Biomes o Plenty causing the crash or loading chunks wrong.
[crash-2016-02-03_13.24.11-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/116275/crash-2016-02-03_13.24.11-server.txt)

Crash report contains the "Already Decorating" error which seems to be associated with it, causes a hard crash.
I will provide the log and crash report as attachments
[fml-server-3.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/116274/fml-server-3.txt)

**Comment by enterprise12nx** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/1702
@Robotia @iKaneki-Ken

**Comment by iKaneki-Ken** [comment]
I've personally never experienced this issue before. It may be an ATG compatibility issue with Thermos.

**Comment by enterprise12nx** [comment]
Ya i reported it, but Robotia says its not his side

**Comment by iKaneki-Ken** [comment]
It's not, I found out that that particular issue was being caused by ChickenChunks spot loaders.

**Comment by enterprise12nx** [comment]
since its running on a server i have 
"#The number of ticks to wait between attempting to unload orphaned chunks
cleanuptime=0 

why would spot loaders cause this?

**Comment by iKaneki-Ken** [comment]
@enterprise12nx Try running the server without ATG, let me know if the problem still persists as I have a strong suspicion that it's ATG causing it.

As well, the Spot Loaders only crashed the server as it was loading Botania's travelling Mana Bursts. But because Mana Bursts can't chunk load and because their destination was outside of the chunk that the Spot Loader was loading, the Mana Bursts caused a slow stack overflow exception which eventually crashed the server.

**Comment by enterprise12nx** [comment]
im not using Botania, and this is on a dedicated server so removing ATG would destroy a lot of things

**Comment by iKaneki-Ken** [comment]
Try running a test server for a bit without ATG.

And what I said previously was in regards to the crash that I posted a few months ago that you linked in a post of yours further up.

**Comment by enterprise12nx** [comment]
ok, i'll give it a try when i have time, gonna see what BOP people gotta say, maybe will report it to ATG as well

**Comment by Adubbz** [comment]
We really have never supported Cauldron for the same reason we don't support Optifine - Unpredictable breaking changes to both Minecraft and Forge that we have no desire to keep track of. Additionally, with so many mods potentially causing problems, it becomes almost impossible to identify who is really at fault.


However, I've mentioned this in another issue and i'll say it again here - We've mostly moved what time we do get over to being spent working on 1.8.x version. Almost none of our work on 1.7 can be reused on 1.8 and vice versa, which makes it counterproductive. I'm closing this because I can say almost certainly that we won't be looking at this. We still review and accept pull requests for that version, but beyond that, not much else.

**Comment by enterprise12nx** [comment]
@Adubbz but 95% of modded servers use 1.7...because most mods are skipping 1.8

Like i also said, i was getting this issue after updating Biomes o Plenty, it even says it in the log its from biomes o plenty..
This even happens in normal forge, ive done countless tests because i was asked to prior to making this request, cauldrons pretty much the only thing left running modded servers with plugins for 1.7.10, which is what people like, i dont really know people who come to play SSP anymore.

Leaving a broken version is really not cool

**Comment by Adubbz** [comment]
I'm aware that people seem to be sticking with 1.7, and that's fine, but I feel it's unfair to have the choices of others to hold back forced upon those that wish to move forward. There comes a point when it's time to move on and we've chosen to take that path. 

Also, at the moment there's only two of us; myself and Forstride,. Forstride's mostly an arty guy rather than a programmer, whereas I am very busy and have to juggle modding with real life. With what limited time I have, I would much rather spend it on something that is going to stick with us as we move forward than spend ages tracking down a convoluted bug only to make a throwaway change for a version that's on its way out.
