### ISSUE TITLE
Client crash a few seconds after logging in. 1.9

### ISSUE THREAD

**Issue by josephkimball** [Glitchfiend/BiomesOPlenty#718]
Client loads world but crashes a few seconds later. Upgraded from 1.8 to 1.9, forge reports missing block IDs. Using BiomesOPlenty-1.9-4.0.0.1944-universal.jar.

Any help would be appreciated. Thanks!

Server Log:

> 19.03 13:55:17 [Server] INFO [13:55:17] [Server thread/INFO] [FML]: Found a missing id from the world biomesoplenty:fruit_block
> 19.03 13:55:17 [Server] INFO [13:55:17] [Server thread/INFO] [FML]: Found a missing id from the world biomesoplenty:hard_dirt
> 19.03 13:55:17 [Server] INFO [13:55:17] [Server thread/INFO] [FML]: Found a missing id from the world biomesoplenty:dried_dirt
> 19.03 13:55:17 [Server] INFO [13:55:17] [Server thread/INFO] [FML]: Found a missing id from the world biomesoplenty:wisteria
> 19.03 13:55:17 [Server] INFO [13:55:17] [Server thread/INFO] [FML]: Found a missing id from the world biomesoplenty:dark_door_block
> 19.03 13:55:17 [Server] INFO [13:55:17] [Server thread/INFO] [FML]: Found a missing id from the world biomesoplenty:dark_stairs
> 19.03 13:55:17 [Server] INFO [13:55:17] [Server thread/INFO] [FML]: Found a missing id from the world biomesoplenty:hard_sand
> 19.03 13:55:17 [Server] INFO [13:55:17] [Server thread/INFO] [FML]: Found a missing id from the world biomesoplenty:dark_fence_gate
> 19.03 13:55:17 [Server] INFO [13:55:17] [Server thread/INFO] [FML]: Found a missing id from the world biomesoplenty:ash_stone
> 19.03 13:55:17 [Server] INFO [13:55:17] [Server thread/INFO] [FML]: Found a missing id from the world biomesoplenty:moss
> 19.03 13:55:17 [Server] INFO [13:55:17] [Server thread/INFO] [FML]: Found a missing id from the world biomesoplenty:stone_formations
> 19.03 13:55:17 [Server] INFO [13:55:17] [Server thread/INFO] [FML]: Found a missing id from the world biomesoplenty:dark_fence
> 19.03 13:55:17 [Server] INFO [13:55:17] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance

Client Log:
[crash-2016-03-19_13.39.21-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/180976/crash-2016-03-19_13.39.21-client.txt)

**Comment by TDWPFTW** [comment]
Those blocks were all removed a while back in 1.8.9.  Try opening the world in singleplayer and then moving it over to the server again.

**Comment by Adubbz** [comment]
That specific crash looks like either a Forge or a Vanilla bug. And yeah, those blocks have been removed a while back from the 1.8.9 version also

**Comment by josephkimball** [comment]
Thanks for the quick reply. I was running 1.8.9, so I guess those blocks aren't causing the crash?

I know this isn't really the place to post it, but if it's a Forge issue any suggestions on what to try next?

**Comment by Adubbz** [comment]
Removing the blocks might cause a few oddities in your world, but nothing that should crash. To be sure, you could try updating to the latest 1.8.9 version and loading the world there (the blocks will still be removed).

I would say your best bet would be to first try updating Forge (you're on 1770, latest is 1777), and if that still doesn't work, perhaps open the world in something like McEdit and try removing glass panes/redstone near where you spawn, since those appear to be the culprit from the crash given. 

Also, to determine if it is a Forge issue or not, backup the world and try loading it without any mods. It'll have a lot of missing blocks, but it should still crash regardless unless the redstone or panes are removed as a side-effect. If this is the case, you might want to report it over at https://github.com/MinecraftForge/MinecraftForge/issues

**Comment by Adubbz** [comment]
Closing this for now, it appears this should have been fixed in Forge looking at their commit log. If this is not the case feel free to reopen this.
