### ISSUE TITLE
Loamy grass blocks loading as frosted ice

### ISSUE THREAD

**Issue by KaySuave** [Glitchfiend/BiomesOPlenty#729]
I've got an issue  with a number of blocks loading incorrectly, frosted ice has replaced loamy grass which immediately melts in Moors and Coniferous forest. There's also pieces of endstone brick and bone segments in coniferous forests but I'm not sure what they're replacing. Also crag rock is replaced with ash block and there's honey blocks loading in Groves. 
I was using the Plant Mega Pack mod as well but the blocks load incorrectly with or without PMP running. I've got some screenshots if needed.

____

- Biomes O' Plenty: 1.9-4.0.0.1975
- Minecraft: 1.9
- Forge: 12.16.0.1816

**Comment by Adubbz** [comment]
That's very very odd... Does this issue occur in brand new worlds? Also, what version of BoP was this world created with?

**Comment by KaySuave** [comment]
It's fine with new worlds. The loam/ice world was made with BOP 1.8-3.0.0.1505

**Comment by Adubbz** [comment]
If that is the case, that's not entirely unexpected i'm afraid. We made some pretty drastic changes after updating to 1.8.9 that weren't in the 1.8 version, including many which affected blocks. Only recently has the mod entered a stable state on both 1.8.9 and 1.9, which is why worlds are compatible between those versions. 

Your best bet might be to look for a world conversion tool to fix some of the major blocks, although we also changed how metadata is arranged on many of them too and i'm not sure if that would support it. Things worth looking at would be McEdit (http://www.mcedit.net/) and Midas (https://github.com/agaricusb/midas-silver). Really sorry man :/
