### ISSUE TITLE
[1.10] Trees or grass are not generated in superflat BoP world

### ISSUE THREAD

**Issue by donqixot** [Glitchfiend/BiomesOPlenty#801]
#### Issue Description:
I create superflat world and specify biome to be one of BoP, for instance "redwood_forest": 78 as in following settings:

3;minecraft:bedrock,59*minecraft:stone,3*minecraft:dirt,minecraft:grass;78;village,biome_1,decoration,stronghold,mineshaft,lake,lava_lake,dungeon

When the world is created, biome is indeed Redwood Forest, but no trees at all, not even grass! Despite option "decoration" is set above.

#### Steps to reproduce:

1. create superflat world with biome=78
2. check trees or grass
3. 

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.9.4-4.1.0.2033-universal
- Minecraft: 1.10.2
- Forge: forge 1.10.2-12.18.0.2006-1.10.0

**Comment by Forstride** [comment]
I'm really late on this, but this is because our biomes work differently from vanilla biomes.  We do not use their decoration options, so that our biomes can be completely customizable by users.  That's another reason we have a separate world type and whatnot.

Don't think there's anything we can do about this, aside from creating our own superflat world type, but it's not really a priority.
