### ISSUE TITLE
Config system currently is not useful.

### ISSUE THREAD

**Issue by Claycorp** [Glitchfiend/BiomesOPlenty#814]
So currently there is 4 config options people can see and edit made by default.
FOUR.  
This new config system is an awful idea in its current state. 
Here is why:
 1. Zero examples of complete files. How do you expect people to know the JSON format they need for editing each biome or even other general configs?  

 2. Wiki information is broad and mostly useless to anyone trying to use this system. Examples, examples, examples. If you ever want people to pick up on your almighty config system you need to show them how to use it else they will just use a another mod that is user friendly.  

 3. Simple options that existed before are now moved into a complicated burden of configs. People who like BoP and want to disable X biome or remove poison ivy will not use the mod. They don't want to spend 4 hours trying to figure out some convoluted config system just to remove or enable a feature.  

 4. People regardless of experience or know how will opt for other mods. I have delt with this first hand on a small user base with no other mod available. Pay2Spawn uses a JSON file to store all the data it needs to work but even with an ingame GUI editor and an extensive wiki that took days to write people just said "It's not worth my time for what I want to do."

I understand you want people to have the power to edit things and not overwrite them or they never get the changes but there are other ways to go about it that involve less stress on both sides.  

Examples:
 1. Give all the config options to the user put general options in one location and the rest broken down however they need be. When you push an update that needs to edit the files backup the folder and write a new one. Lycanite's mobs uses this system. It can be annoying but lets people who what to edit whatever do it without knowing how to make the files.  

 2. Make one set of files that always match the default settings of BoP and have the user copy the file into a folder that overrides the defaults. Simple for the users of any skill level and it will include all the required files for the person to edit without guessing anything, AE2 Uses this system for its crafting recipes.

I speak from experience on this I'm not here to just yell empty words at you. I make my own packs, I run servers, I work with tons of people of varying levels of skill and I will avoid BoP even though it was my go to biome mod in 1.7.10 purely because I don't want to spend the time to learn a system that is proven to be nothing but a larger workload on the devs and the users. Please reconsider this system while thinking about what you are doing to the BoP users and yourself.

**Comment by Forstride** [comment]
You're saying this on the assumption that the config system is complete.  It's not.  Adubbz, our lead programmer, is extremely busy, and I am not a good enough programmer to do this stuff myself.  We have no one else working on the mod, and we've been doing this for nearly 4 years, so give us a break, alright?  You don't need to have such an aggressive tone over a mod for a children's video game.

We do want to have default config files that are all filled in by default, and proper wiki documentation, but things take time, and we both have more important things to do outside of modding.  Also, regarding issue number 3, both of those are possible without much fiddling around.

Biomes can be disabled by changing their IDs to -1 in the biome_ids file, and we have options to disable most features (Including poison ivy, quicksand, thorns, etc.) upon world creation in our customization menu.

The "almighty" biome config system is mostly for people who want to really fine tune each biome, like removing a certain type of tree from a biome, or adding a new flower type, etc..  99% of the people who use the mod are not going to need/want to mess with them, which is why they are not a priority.

**Comment by Claycorp** [comment]
It must be complete enough if you are expecting people to use it. Also I never said that you need to complete it or change it. I'm pointing out what my experience has been over the last 5 years and that the step you are taking isn't the best idea.  

Sorry to say but you made the post aggressive in your head. This is constructive criticism and all of it is backed up with facts. There is no hate, no demands, no aggression at all. If you don't like people criticising you, you picked the wrong hobby to do.

Minecraft isn't a children's game. There are tons of people of all ages that play minecraft and I can guarantee that a majority of the people who make modpacks are not children. (That would be some of the people using said configs FYI) Heck I bet most people who download mods are not children! I bet that a majority of the children in modding that download mods likely are getting them from other people because most of the time they aren't capable of understanding what a mod is or how they work. The ones that do are the people the configs exist for.

If you want default configs to be generated that should be the first thing done. Having a config system is totally useless if people can't use it. That's like buying a power mixer when you have no power but perhaps some day you might get power. The wiki information should follow along with whatever works currently with examples. As you add things the information gets updated accordingly.  

Yup you and everyone else has more important things to do IRL. Everyone else seems to get along with others just fine and make their mods work well. Why should I treat some devs specially and others not?  

If 3 is easy to do with no fiddling why is it not in the config or explained anywhere? You posting to this issue gives more information then the config section of the wiki. Thank you for proving my point that the wiki is lacking to the point of being utterly useless.  

Biomes can be disabled by setting their ID's to -1 in the biome_ids file? Thats new information. You should put that in the wiki. Also there's an editor to edit the world generation before you make it? That's also new information. Also likely should be in the wiki. Side note: You still shouldn't expect people to edit the world gen every time they make a new world. That is silly.  

I don't think you understand the point that is being made. There is four options for people to edit and zero mentions of any other systems for changing things that were in the CFG before. Most of those options were completely fine the way they were implemented. Don't want thorns? thorns=false Don't want ivy? ivy=false Don't want gems? gems=false These are some examples of options that don't need any other way of editing them other than an entry in a config file that says true or false.  Why make it complicated or rely on the user to do all the work?

**Comment by Forstride** [comment]
"Sorry to say but you made the post aggressive in your head. This is constructive criticism and all of it is backed up with facts. There is no hate, no demands, no aggression at all."

Telling me you're not going to use BOP is not constructive.  Why should I care what you have to say if you've just sworn off the mod because of a feature that the majority of users do not need/want to use?  We have MUCH more important things that need to be added to the mod, and with what limited time we have to work on it, you can guarantee those things will be coming first.

-----------------

"Yup you and everyone else has more important things to do IRL. Everyone else seems to get along with others just fine and make their mods work well. Why should I treat some devs specially and others not?"

I'm not asking you to treat us differently.  I'm not asking you to treat us in any way.  I'm telling you how it is, and why things are the way they are.  We owe **nothing** to you, or anyone else who uses the mod.  Want things done faster?  Contribute with a pull request.  Don't like it?  Use another mod, or make your own.

---------------

"Thank you for proving my point that the wiki is lacking to the point of being utterly useless."

Thank you for proving my point that you are being passive aggressive.  Oh, sorry, I guess that was meant to be "constructive criticism."

**Comment by Silvrus** [comment]
Forgive me for necro'ing this, but I have to agree, I've been racking my brain trying to figure out how to remove biomes from spawning with no luck. Setting the Biome ID's to -1 as suggested doesn't seem to prevent them from spawning, I can only imagine I'm writing the configs wrong but I can't seem to find an example of how to do them correctly. I've been working with other modpack devs trying to figure it out without luck. 
I like the option given to make BoP the default for world generation, but I would like it to go further, so that I can make things like [Temperature:Lattitude], [Rain:Random] and [Landmass:Continents] be the default, with perhaps turning off some generation like gems and poison ivy. If there is somewhere with examples of how to do this, I would be most appreciative to be pointed there.

**Comment by Darkosto** [comment]
I'm also going to throw my two cents into here. Everything I saw is from a modpack developer standpoint:

I can understand your argument of creating a method of keeping the player up to date on configs by using this new method. However, this new method is extremely difficult to figure out. When I have to consult 5 people and none of us figure out how to make it work, then something might need to be adjusted. So, what happens is I don't want to spend more hours trying to figure the system out that you have in place and look for alternatives. I would even consider attempting to customize configs if there were at least example files posted. 

Many of the users won't mess the config, you're correct. But, many of those users will be using a version that has been customized by a modpack developer. Which, at the moment, isn't really happening. Is the mod in development? Sure, but it's difficult to help push modded players into a new minecraft version without good modpacks and customization to help with that transition. Is your time valuable? Of course. So is mine, and it's extremely frustrating to spend it failing at making configs. 

Would I like to use the mod? Absolutely. Can I set the mod in a way that will work with my ideas and specifications? Not right now I can't. I assume I'm able to set weights of all biomes or turn off certain biomes but I can't get it to actually work. I'm not a dev who just throws mods in a folder and calls it a day, I actually take the time to configure mods to fit the overall scope of the pack, which I would love to do with BoP. 

At the end of the day, we have some big projects coming up at FTB and I would love to customize this mod for use in our packs. What would work best for me personally? Example configs. I would benefit greatly from them.

**Comment by Forstride** [comment]
Again, I said the config options were **incomplete.**  I don't know if you guys are just missing that or what...

It's not set in stone, so quit acting like it.  The problem is that **we do not have enough time between the two of us to do anything about it.**  I personally wouldn't even know where to begin with this, so it would be something that Adubbz would have to add himself.  I feel like I explained this well enough in my first reply.
