### ISSUE TITLE
Forge's bucket texture gets changed with BoP

### ISSUE THREAD

**Issue by Hallo89** [Glitchfiend/BiomesOPlenty#887]
#### Issue Description:

Forge obviously changes the bucket texture in 1.10.2 modpacks. If Biomes o' Plenty is installed, this bucket texture uses the colors of the vanilla bucket, the shape itself is the same tho.

#### Steps to reproduce:

1. Launch a modpack with Biomes o' Plenty installed and look at the bucket texture
2. Remove BoP
3. Launch the modpack again and look at the bucket texture again

#### Additional Information:

-Without BoP/With BoP
![unbenannt](https://cloud.githubusercontent.com/assets/21200815/20061658/fe197a44-a500-11e6-9644-a1edca0d5d16.png)
(Used the texturedump mod to get the textures)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.10.2-5.0.0.2091-universal
- Minecraft: 1.10.2
- Forge: 12.18.2.2122

**Comment by GirafiStudios** [comment]
I'm pretty sure this is intended. BoP have a config option to turn this off.

**Comment by Hallo89** [comment]
Why tho, you can't just say the bucket texture is nicer and override it without saying anything :|
I like the original forge one for example

**Comment by GirafiStudios** [comment]
I don't know, I didn't add it! Personally I don't like Forges or BoPs texture.

**Comment by Hallo89** [comment]
Guess I can close this issue then but consider adding a message in the chat when the world is created or something like this, that would be nice :D

**Comment by Adubbz** [comment]
As far as I know there isn't anywhere where we've publicly given the reasoning for this, so I thought I'd take the opportunity to do so here.

Towards the start of the year, myself and Rorax argued with the Forge developers over the texture for the universal buckets because it fit in with none of the other textures in the game. Note that this should be a big no-no for something which is supposedly only for mod compatibility. We both understood the reasoning for the decision (to avoid *potential* legal issues which arise through distributing Mojang's textures), and provided an alternative.  Here's a summary of the argument from memory:

**Us:** The current texture is inconsistent with Vanilla, it uses slight variations of the same colour and shading, compared with Vanilla textures which use drastically different colours within the same texture and lack shading. We understand the legal problems you face, so here's an alternative that uses the same shape as the Forge bucket, but with fixed colouring.

**Them:** Too late, no more input is allowed. What's this, you weren't informed? That's such a shame, too bad. Oh, and it looks fine to me, and that's all that matters. Are we done with this conversation?

It quite honestly baffles me why they didn't take the solution that was handed to them on a silver platter, but anyway... After that, Rorax was blocked on IRC by the developers, and I added the code for the 'bug' you see before you today.


Interesting fact

Dispute

What BoP is about

Direction of Forge

And for what it's worth, I personally dislike them both as well. Although for me, it's because Forge's lacks any sense of appreciation of the importance of colour  (although I guess some people like this?), and the other just isn't the Vanilla bucket (the original will forever be the best, plus it lacks the try-hard animated fluids).

**Comment by Adubbz** [comment]
There we go, there's the whole comment. I really need to look before accidentally posting too early in future >_> Looks like I reopened it too when I shouldn't have...

**Comment by Hallo89** [comment]
Thanks for describing it :P I understand, and I guess my problem is just that I always played minecraft with a texturepack, which is why I don't like the vanilla bucket colors and like the Forge colors as it is in the style of CyanideX  (I'd say, maybe he did even do it, dunno), and his textures make up a big percentage of the textures of modded minecraft, which is why I got used to them, lol. And yes, it's not a texturepack with much mod support :p
