### ISSUE TITLE
[REQUEST/FEATURE] Bring back old Sacred Oaks with big trunks?

### ISSUE THREAD

**Issue by bounceraff** [Glitchfiend/BiomesOPlenty#898]
In the 1.10.2 build of BOP, I'm seeing only Sacred Oaks with a 2x2 trunk. It'd be nice to have the old, bigger 5x5 trunks back, I miss them.

If I'm wrong and they do still exist with the bigger trunks, please let me know where because all I've been able to find are 2x2 ones (and I've searched many sacred springs biomes)

BiomesOPlenty-1.10.2-5.0.0.2093-universal

**Comment by FELITH** [comment]
yeah please bring it back, I very love the old texture. for now sacred oaks is similar to oak with vines for me.
:(

**Comment by Iteries** [comment]
I have not updated since the loss of some special items.  I had to back date just to get them back.  Could it be possible to the above request and add in the HOT SPRING WATER BUCKET too?  Please, one needs their hot soaking from mining all day and the minions will revolt without one! (j/k) but in our lan group it was a major bonus with the Japan setting to find a Hot Spring or make a bathtub with bubble water.

**Comment by xAlicatt** [comment]
Technically, you could just add extra blocks around the base of the tree after you grow it to make it thicker. I know it's not exactly the same, but it's an option.

**Comment by Forstride** [comment]
I'm going to be removing the Sacred Springs (Along with Sacred Oak trees) in MC 1.13, so I'm just gonna close this issue.

**Comment by xAlicatt** [comment]
Why in the world would you do that?

**Comment by Forstride** [comment]
Well for one, due to having so many leaves, the biome causes framerate drops for a lot of people.  Second, the trees don't even generate properly half the time, with their trunks just not generating for some reason.  And I just don't really like the design of the biome, and can't really see a way to redesign it without changing it into an entirely different biome, so I'm just removing it.

**Comment by xAlicatt** [comment]
I miss the 1.7 generation of the biome anyway...had more height variation/cliffs. I assumed that the redesigned trees was because they would sometimes generate with chunks missing out of them and because they could cause significant fps drops...but it's one of the few very unique "pretty" biomes in the mod, and it makes me sad to see it go.
