### ISSUE TITLE
[1.11] Woodland Mansion not generating

### ISSUE THREAD

**Issue by hennign** [Glitchfiend/BiomesOPlenty#910]
#### Issue Description:
Woodland Mansion doesn't seem to be generating when mod is enabled. Tested this with just Biomes o' Plenty enabled.

#### Steps to reproduce:

1. Generate new world with Biomes o' Plenty enabled.
2. Use '/locate Mansion'.
3. Feature not found.

#### Additional Information:
Also tested by attempting to unlock Cartographer tier 4 trades, but they would only unlock to level 3.

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 6.0.0.2110-universal
- Minecraft: 1.11
- Forge: 13.19.0.2153

**Comment by Syndaryl** [comment]
Are you sure that it's not generating, or that /locate isn't working? I can stand in the middle of a village and /locate Village still doesn't work. I walk 200 meters away, it still doesn't work. I'm not sure it's very reliable right now.

**Comment by Syndaryl** [comment]
Did a little testing, /locate doesn't seem to work in BIOP world types. I am going to guess some kind of custom code needs to be done for new world types, since the way they generate would be different in each worldgen algorithm.

**Comment by srs-bsns** [comment]
@Adubbz 
The BoP chunk generator needs to be updated to add a generator for `net.minecraft.world.gen.structure.WoodlandMansion`..
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.11.x-6.0.x/src/main/java/biomesoplenty/common/world/ChunkProviderGenerateBOP.java#L108

The problem here, however, is that the `WoodlandMansion` constructor specifically requires a `ChunkProviderOverworld` object passed to it, which `ChunkProviderGenerateBOP` is not. I've had neither the time nor the inclination to look into this issue too deeply yet (we need to add a generator to RTG as well), so I'm not sure why there's a dependency on `ChunkProviderOverworld`. This might be able to be mitigated by a patch in Forge, changing `ChunkProviderOverworld` to `IChunkGenerator`, provided that `WoodlandMansion` doesn't need to reference anything outside of the interface.

Just a FYI: `net.minecraft.world.gen.structure.MapGenEndCity` has this same limitation by requiring a `ChunkProviderEnd` object passed to it.

**Comment by Shirotatsu** [comment]
Has there been any updates with this issue? can the new woodland mansion and end cities spawn with this mod? Some friends and I were thinking of starting a new server on 1.11 with this but I couldn't find any more info about if the new content would work.

**Comment by GirafiStudios** [comment]
End cities can spawn yes. Currently BoP don't mess with the Nether or the End generation.

**Comment by Shirotatsu** [comment]
That's good that end cities spawn. so is the woodland mansion still not working?

**Comment by srs-bsns** [comment]
No, AFAIK, a Woodland Mansion generator hasn't been added yet. See my previous message.
