### ISSUE TITLE
1.11 BoP "Customize World Settings"

### ISSUE THREAD

**Issue by Makomea** [Glitchfiend/BiomesOPlenty#912]
My apologies if this isn't the proper place or setting to ask this, but can anyone give me a basic description of the world customization settings when you create a new world? I have never used this mod before and I have really searched for a readme or wiki that has a description, checked all the curse forge project sites.  Really there is just a general lack of introductory info anywhere. I am not complaining or anything, it does what it says on the main sites, "adds a slew of biomes to minecraft." ^_^ It would be nice though if there was a tool tip to pop up with at least a short description to "Biome Size", "Temerature", "Land Mass", "Rainfall", and "Amplitude". I am sure "Biome Size" tiny-huge is similar to choosing between default, large, and extreme biomes in default Minecraft but Landmass is a bit more cryptic, Vanilla I assume is just regular world generation?  Continents and Archipelago's, I am familiar with the geological terms in real life, just not how they apply to BoP. Do they limit the world size instead of having an infinitely generated landmass in favor of a specialized and more polished world to explore? "Temperature" and "Rainfall" I am not sure at all what they affect other than they have the same settings (Aside from one extra setting, LATITUDE for Temperature, there are SMALL_ZONES, MEDIUM_ZONES, LARGE_ZONES, and RANDOM) and finally "Amplitude".  What are these settings and how are they changed/modified by zones/latitude. Also, Amplitude, does that apply temperature and/or rainfall? If so, in what way does increasing/decreasing amplitude affect them?  For now I am going to try BoP for the first time with default settings but eventually I would like to change things up a bit after I have an understanding of the settings to get the best possible experience with this awesome mod with Tough as Nails. ^_* Thank you guys very much for any and all information, it is greatly appreciated. Also, thank you to the mod Author for creating and sharing it with us!

As an aside: Page 2 of the BoP customization menu is blank.  I am not sure if that is by design or not. I am using latest MC version with latest BoP for 1.11 using Forge-1.11-13.19.0.2159 if that helps.

**Comment by Syndaryl** [comment]
**From experience**

- Biome Size controls the extent of biomes - little tiny patches, vast expanses. It is not significantly influenced by other dials
- Temperature influences which biomes are picked. Biomes are roughly grouped into cold, warm, and temperate. Temperature spread by latitude means that temperature should get colder away from 0,0, otherwise small/medium/large covers clumping of biomes of similar temperatures, so you're more likely to have a jungle next to a desert than have a jungle next to a tundra. Random means you get whatever.
- Rainfall is like Temperature, but controls wet/normal/dry biomes. 
- - Every biome is assigned a Temperature and a Rainfall level - these two settings combined control biome distribution
- Land Mass does not constrain your world. Continents uses an algorithm that tends to produce big stretches of uninterrupted terrain, archipelligos uses an algorithm that tends to produce lots of strings of islands.
- Amplitude is the heightmap. A low amplitude will produce a largely flat world, smoothing out bumps, a high amplitude will turn bumps into hills, hills into mountains, and mountains into alpine pillars. I can't imagine what alps would look like.

**Comment by GirafiStudios** [comment]
As for the page 2 being plank. It is just not implemented yet. Mentioned here https://github.com/Glitchfiend/BiomesOPlenty/issues/623

**Comment by Makomea** [comment]
Thank you so much Syndaryl and GirafiStudios! That is a huge help ^_^ To return the favor, giving the ratio of bumps to hills, hills into mountains, and mountains into alpine pillars... the alps would resemble Olympus Mons on Mars! =^_^= I know, too cheesy haha, thanks again guys.

**Comment by Adubbz** [comment]
Looks like this has been resolved. The empty page is part of https://github.com/Glitchfiend/BiomesOPlenty/issues/623
