### ISSUE TITLE
BiomeBundle compatibility?

### ISSUE THREAD

**Issue by hhiru** [Glitchfiend/BiomesOPlenty#936]
I'm not expecting anything fast but I wanted to know if you ever considered a compatibility version using the TerrainControl API. I know it is not your fault if TerraiControl can't work if both BoP and TerraiControl are present in the same mods folder but having a collab between you and TerrainControl (more precisely BiomeBundle) would make the best possible world for minecraft. Maybe porting everything it is not feasible right now, but trying to use one of your biome as test and porting the other custom items and blocks may open the way to people willing to help just for the sake of the best experience possible.

Did you already try testing your bundle using TerrainControl? Do you care, or are able to do so since you are not working at this mod only? I don't want to make any demands here, I love what you did and honestly I do not play modpacks if your mod is not present, so what I'm doing here is a honest and kind request of information and nothing more. Thanks again for your hard work :)

**Comment by Adubbz** [comment]
No, integrating Terrain Control is far too much work that neither myself nor Forstride wish to commit ourselves to, and it's something neither of us really have interest in. In terms of biome bundle itself, here's my overall thoughts.

As you know, Biome Bundle is essentially a set of config files that alter the terrain and decoration of Vanilla biomes rather than adding new ones, there's just no way around that. Biomes O' Plenty and pretty much all other biome mods except Biome Bundle add _real_ new biomes and do terrain generation and decoration in actual code, hence, they're not 'bundles'. As a result, collaborating with the biome bundle developers really isn't possible, as this seems to indicate that they don't have an understanding of code. 

Even still, if they do have an understanding of code, I question their decision to develop their mod in its current form, especially given the rather significant performance problems. With BoP seemingly already being blamed for slowing down people's game, I can't possibly imagine how much blame we'll get when Biome Bundle slows the game to a halt.

Overall, unless you're _only_ using Biome Bundle in your game, I'd really recommend any other biome mod over it, even if that means you don't use BoP. It simply isn't designed to integrate well with other mods.
