### ISSUE TITLE
What ID range BoP uses for its biomes? [TerrainControl Issue]

### ISSUE THREAD

**Issue by hhiru** [Glitchfiend/BiomesOPlenty#945]
- [X] Biomes O' Plenty is updated to the latest available version
- [ ] This issue occurs with Minecraft 1.11. **WE DO NOT SUPPORT MINECRAFT 1.7.10, 1.8.9, 1.9.4, 1.10.2 AND ANY VERSIONS BELOW THAT!  YOUR ISSUE WILL AUTOMATICALLY BE CLOSED IF IT IS PERTAINING TO THOSE VERSIONS!**
- [X] Forge is updated to the latest available version
- [X] This issue occurs without Optifine, Cauldron or similar mods installed
- [X] All other mods which appear to be involved are updated to their latest versions
- [x] This issue does not occur in a modpack (If it does, please report this to the modpack author)

----

#### Issue Description:

I already opened a thread before asking for a BiomeBundle compatibility but I'm back asking for informations about the dynamic biome ID assignation. As you can see in [this](https://github.com/Shinoow/AbyssalCraft/issues/189#issuecomment-276675798) ticket I opened on a different github page for a different mod that adds new biomes, a guy suggested me to edit the biome ID range that TC was using because it was conflicting with the biome ID range that the mod was using too! Maybe I can bypass the incompatibility between the mods using a different ID range. What do you think?

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.10.2-5.0.0.2142-universal.jar
- Minecraft: Minecraft 1.10.2
- Forge: 1.10.2 - 12.18.3.2185

**Comment by Adubbz** [comment]
The biome ids used by Biomes O' Plenty may be found and changed in the biome_ids.json config file. These have no specific range, as they are chosen simply based on what is available when the mod is first run.

**Comment by hhiru** [comment]
I tried running BoP once while TerrainControl was loaded too and there was a conflict between BoP IDs and TC IDs. Changing IDs in the TC config file made BoP work with TerrainControl. BoP items and blocks started being generated in TC new biomes! Here's the config file that I made to make AbyssalCraft and BoP work with (or at least this solved the initial generation loop of the world):


[WorldConfig.zip](https://github.com/Glitchfiend/BiomesOPlenty/files/746408/WorldConfig.zip)

**Comment by Adubbz** [comment]
If you press f3 whilst in one of Terrain Control's 'biomes', you'll probably notice that it has the name of a regular Vanilla biome, despite it not necessarily being that biome. This is a setup that introduces a bunch of problems with both BoP and TAN, as BoP will attempt to decorate these 'biomes' as if they were Vanilla biomes, because they are. 

Terrain control really isn't designed with mods in mind, even though it is indeed compatible with Forge. ATG/RTG or other similar mods really are much better in this regard.

**Comment by Adubbz** [comment]
It's worth noting also, biome ids are still limited to being from 0 to 255, all those other ids in terrain control's config are fake

**Comment by hhiru** [comment]
What I like about Biome Bundle is the variety of biomes and structures I can find, not the TerrainControl itself. I was looking for a sort of win-win solution and this ID thing seems to work since I really appreciate what BoP introduces in the game other than its biomes. Maybe I should ask BiomesBundle's author if it is possible using RTG too instead of TC. Not talking about a full port but only to test the mod and see if there are as much features as he needs to make the bundle. Having both BoP and BB would be the best.

I just wanted to report here a solution to the world generation at least since if you try to use BoP and BB without edits the world does not even load. 

> It's worth noting also, biome ids are still limited to being from 0 to 255, all those other ids in terrain control's config are fake

the config file says:
> # The available ids range from 0 to 1023 and the ids 0-39 and 129-167 are taken by vanilla.
> # The ids 256-1023 cannot be saved to the map files, so use ReplaceToBiomeName in that biome.

Using unique IDs still solve the problem. I don't know why but it does

**Comment by Adubbz** [comment]
Yeah, terrain control achieves these additional ids by reusing those of existing biomes only with different terrain and decoration. Behind the scenes, there can still only be 256 biomes which is why certain biomes have strange names with the f3 debug screen. In BoP, we check for these specific Vanilla biomes when adding extra decoration like grass, flowers etc. So even though they may appear to be different biomes visually, technically the ids they're allocated still belong to that of a Vanilla biome, so as far as we know it's still Vanilla biome we're decorating. I understand what you're trying to achieve, although I'm not sure there is any way around the issue you're describing.

**Comment by hhiru** [comment]
I appreciate you are taking your time to explain me how these mods work. Thanks!

**Comment by Adubbz** [comment]
Double check if the decoration issue is only happening in biomes with Vanilla names. If that is the case, I could add the option to disable our added decoration, although it will mean that Vanilla biomes will look off compared to the rest of our biomes

**Comment by hhiru** [comment]
It does but it is fine to me honestly. Since I can't use BoP biomes at least I can have BoP blocks and items
![2017-02-02_03 44 12](https://cloud.githubusercontent.com/assets/11262717/22535218/e56f7682-e8f9-11e6-9181-57cc18fb8cbd.png)
