### ISSUE TITLE
Biomes o’ Plenty’s grass and dirt blocks aren’t supported by other mods

### ISSUE THREAD

**Issue by PapiDimmi** [Glitchfiend/BiomesOPlenty#982]
_E.g._, the farming station from [Ender IO](https://minecraft.curseforge.com/projects/ender-io) doesn’t work with Biomes o’ Plenty’s silty dirt, silty grass, loamy dirt, loamy grass, _etc._.

Also, saplings from [Pam’s Harvestcraft](https://minecraft.curseforge.com/projects/pams-harvestcraft) cannot be planted on dirt and grass blocks from Biomes o’ Plenty.

**Comment by Adubbz** [comment]
This is because those mods check specifically for Vanilla dirt and grass, and there's not really anything we can do about that. For example, EnderIO does the following: https://github.com/SleepyTrousers/EnderIO/blob/11e874b89e05008dfd7cf2c25566da4efa1215ff/src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java#L163

As far as I can tell, there's not any event to hook into this. Pam's would also likely be performing similar checks.
